### ISSUE TITLE
Shooting mechanics

### ISSUE THREAD

**Issue by Kopla-BR** [nexusnode/crafting-dead#10]
Shots can **pass through** some blocks, such as **FENCER**, **DOORS**, **GLASS**, **LEAVES**, among others.

As with version 1.6.4, this modification improves the gameplay strategy.

It's a suggestion linked to the client side, in order to avoid overloading the machine the server is running on.

**Comment by Afarion1** [comment]
#14

**Comment by Kopla-BR** [comment]
Solved.
