### ISSUE TITLE
loot

### ISSUE THREAD

**Issue by BirotoTV** [nexusnode/crafting-dead#109]
Me in version 1.15.2 I don't have loots, how am I supposed to get weapons?

**Comment by josephtarbit** [comment]
1. 1.152 isn't supported.
2. If you mean 1.16.5 then you craft them. Use JEI to view recipes because they're not documented anywhere as of yet.

**Comment by HydrogenC** [comment]
How to obtain bullets since there are no recipes in JEI then?

**Comment by josephtarbit** [comment]
Why are you commenting on a closed issue from 6 months ago...

Also, the issue tracker is for bug reports, your question is more suited to the Discord.
