### ISSUE TITLE
Generating Structures 

### ISSUE THREAD

**Issue by Equilegic** [nexusnode/crafting-dead#110]
I have tried multiple times to get my private server to run this mod. I have the latest version of the mod installed, everything works apart from the auto generating of the mod buildings. 

I have tried everything I can think of but nothing works. Adding CD or Crafting Dead into my server properties level type setting and to generator settings too.

can someone please help me with where to change in order for my server to spawn the buildings in

**Comment by josephtarbit** [comment]
There is no auto generation of structures as of yet.

**Comment by Equilegic** [comment]
Oh right , so the latest version of the mod doesn’t have auto generate structures? How are you supposed to pick up the loot drops that usually spawn in them then? As that’s the whole premise of the mod? Having loot to pick up and scavenge for?

**Comment by josephtarbit** [comment]
The purpose of the mod is primarily guns and zombies. Everything is craftable now, if you want loot there's an additional mod you can download which adds loot blocks.

**Comment by Arownicc** [comment]
could we have a new mod for crafting dead structures then?

**Comment by Equilegic** [comment]
Oh nice okay, so what’s the mod that add loot?

**Comment by josephtarbit** [comment]
https://www.curseforge.com/minecraft/mc-mods/hallzmines-crafting-dead-server-core
