### ISSUE TITLE
[Issue] Armor not work.

### ISSUE THREAD

**Issue by SmileYik** [nexusnode/crafting-dead#112]
Hello author.
In my test, I found that the weapon made damage on a player which put on armor as same as a player which have not armor.
And for all of guns can one shoot to kill a player if hit his head.

Minecraft: 1.16.5
CraftingDead: 1.28-1.41.

**Comment by josephtarbit** [comment]
Which armour are you referring to?

**Comment by SmileYik** [comment]
all.

**Comment by josephtarbit** [comment]
Closing as can't reproduce.
