### ISSUE TITLE
Crafting Dead Immerse crashes the game on load.

### ISSUE THREAD

**Issue by Arownic** [nexusnode/crafting-dead#116]
Once I added Crafting Dead Immerse in my mods folder, it would crash when loading. If I remove Immerse, it works. I have Crafting Dead Core 1.4.0-alpha and Crafting Dead Virus 1.0.0-alpha
 
I've tried 36.1.0 and 36.1.23 and both don't work. Could you make a working release, please?

**Comment by josephtarbit** [comment]
Immerse is still a WIP but send your crash report anyway.
