### ISSUE TITLE
#61 Crash

### ISSUE THREAD

**Issue by ghost** [nexusnode/crafting-dead#117]
Forge 36.1.24, Java 15, not install other mod.
[debug.log](https://github.com/nexusnode/crafting-dead/files/6563152/debug.log)

**Comment by josephtarbit** [comment]
Mod version?

**Comment by ghost** [comment]
https://github.com/nexusnode/crafting-dead/actions/runs/869581503

**Comment by josephtarbit** [comment]
That isn't configured for production as of yet, wait until a release.
