### ISSUE TITLE
Five-Seven's name is wrong

### ISSUE THREAD

**Issue by Arownic** [nexusnode/crafting-dead#119]
![image](https://user-images.githubusercontent.com/67923888/120121447-24ea6500-c169-11eb-9c7d-c8e4a74bf755.png)
wouldn't prioritize this but something to do before the next release

**Comment by josephtarbit** [comment]
What?

**Comment by Arownic** [comment]
was that intentional?

**Comment by josephtarbit** [comment]
That is how the gun's name is officially branded

**Comment by Arownic** [comment]
my bad didn't know it was supposed to be with a capital N
