### ISSUE TITLE
Acog and reddot both shoot low.

### ISSUE THREAD

**Issue by Hallzmine** [nexusnode/crafting-dead#12]
Both the sights acog and red dot seem to fire low. The acog sight just feels off as well, compared to 1.6.4's acog.[https://youtu.be/mbg5S7zyKUg](url)

**Comment by Kopla-BR** [comment]
**[GUNS]** - Some weapons have problems rendering the attachment.

Red Dot Sight:
	
	* M4A1, ScarH, FN-FAL, HK-417, MPT, Sporter 22, G36C, M240, RPK, MK48, G18,
	  M1911, P90, Vector, P250, MAC-10, MP5A5, M107 and AS50

Acog sight:
    
    * Every weapon that accepts this attachment, with the exception of DMR.
