### ISSUE TITLE
Shader

### ISSUE THREAD

**Issue by Ligma21** [nexusnode/crafting-dead#121]
With shader when I put on some armor like vest and gas mask etc. its like purple and black box how can I fix it

**Comment by josephtarbit** [comment]
Is it optifine?

**Comment by Ligma21** [comment]
yes

**Comment by Ligma21** [comment]
> Is it optifine?

do you know how to solve this?

**Comment by josephtarbit** [comment]
No, this is Optifine's problem. Optifine is closed source so I have no way of fixing this - they hack into a lot of Minecraft's internals so generally end up breaking a lot of mods. I suggest trying something like [sodium](https://github.com/Pannoniae/sodium-forge) or [chlorine](https://www.curseforge.com/minecraft/mc-mods/chlorine).
