### ISSUE TITLE
About odd shotgun firing

### ISSUE THREAD

**Issue by TheEvilEye05** [nexusnode/crafting-dead#122]
When you fire a shotgun, it first shots all the rounds, and then the sound of the shot plays and the recoil is shown. It's a little weird and very umcofortable

**Comment by josephtarbit** [comment]
Could you show me a video demonstrating this as I can't recreate it?

**Comment by TheEvilEye05** [comment]
Sure. 
Look, there's a little delay when I press the shoting button and when the shot sound plays and the recoil feels, the bullets are fired with no delay, but it's kinda weird

https://user-images.githubusercontent.com/84248306/121249582-5a2e3b80-c86a-11eb-94af-e0c3b9c4dcca.mp4

**Comment by josephtarbit** [comment]
Hmm that's very strange, I'll look into it

**Comment by josephtarbit** [comment]
Mod version?

**Comment by TheEvilEye05** [comment]
crafting-dead-core-1.16.5-1.5.0_h1-alpha

**Comment by josephtarbit** [comment]
What mods do you have installed?

**Comment by TheEvilEye05** [comment]
![image](https://user-images.githubusercontent.com/84248306/121268699-0cbec800-c884-11eb-8869-2bd5daff05b0.png)
![image](https://user-images.githubusercontent.com/84248306/121268730-19dbb700-c884-11eb-9252-be050442973f.png)

**Comment by josephtarbit** [comment]
Can you test with only crafting dead?

**Comment by TheEvilEye05** [comment]
Still doing that weird firing, look:

https://user-images.githubusercontent.com/84248306/121403622-b358a680-c920-11eb-95f6-92655cc00ad6.mp4

here are the only mods:
![image](https://user-images.githubusercontent.com/84248306/121403805-e733cc00-c920-11eb-8ce5-53123c938330.png)

**Comment by josephtarbit** [comment]
And it doesn't do that with any other guns?

**Comment by TheEvilEye05** [comment]
I haven't tried all of them, but most of the guns don't do that

**Comment by josephtarbit** [comment]
Can you try with only crafting dead, no other mods at all? I can't reproduce this so I have no idea what's causing it.

**Comment by victorbetoni** [comment]
It's probably optfine's fault. Try disabling the option "Lazy Chunk Loading", worked for me

**Comment by TheEvilEye05** [comment]
> Can you try with only crafting dead, no other mods at all? I can't reproduce this so I have no idea what's causing it.
I'm gonna try

**Comment by TheEvilEye05** [comment]
> It's probably optfine's fault. Try disabling the option "Lazy Chunk Loading", worked for me
Thank you, I'm gonna try that too

**Comment by josephtarbit** [comment]
Any updates on this?
