### ISSUE TITLE
NBT Tag Overload

### ISSUE THREAD

**Issue by TqLxQuanZ** [nexusnode/crafting-dead#125]
Hello there, I have found a bug problem which might cause a lot more trouble in the future. This is quite a problematic bug when it comes to modpack. When equipped with guns, the player will be filled with "minecraft:vanishing_curse" which I believe the source comes from the guns, and whenever firing the guns(Or killed enemies, not sure which one) they just keep non-stop adding more and more. 

I have another mod added in called Corpse, which duplicates carries over player's inventory and creates a corpse based then move into it, this often leads to the gun's massive "vanishing curse" enchantment nbt tag being moved over and leading to a payload error because it gets too massive (Assuming corpse has its own nbt tags as well). I assume other mods like refined storage/applied energistic 2 which stores a tons of nbt tag storage mods, or storage that has a lot of guns/magazines put in might have a similar problem.

![image](https://user-images.githubusercontent.com/31058251/121232900-9ee6c080-c8c4-11eb-804e-e3c7da033ffe.png)

At last, great mod btw, I really like it and having fun with my friends shooting each other's heads.

**Comment by josephtarbit** [comment]
I'll look into this, thanks for reporting

**Comment by josephtarbit** [comment]
Are you using a normal server (not Arclight or something)?

**Comment by TqLxQuanZ** [comment]
Yup, it is a normal server. Forge version doesn't seem to matter since I tested several versions.

**Comment by TqLxQuanZ** [comment]
My apologies, I found out that it belongs to another mod causing such issues.
