### ISSUE TITLE
"Container Click" Crash

### ISSUE THREAD

**Issue by lartts** [nexusnode/crafting-dead#126]
Crash Report:
https://pastebin.com/GTHZxw9E

**Comment by SquirrelloDev** [comment]
Same for me
[crash-2021-06-14_20.04.57-client.txt](https://github.com/nexusnode/crafting-dead/files/6650422/crash-2021-06-14_20.04.57-client.txt)

**Comment by victorbetoni** [comment]
Which build did you use? How do you reproduce this crash?

**Comment by lartts** [comment]
Latest version, it crashes when I put the gun in the gun customization slot after I customized a gun,

Basically I can only customize a gun once, otherwise an inevitable crash will occur.

**Comment by victorbetoni** [comment]
> customization

Latest version you mean the latest release? crafting-dead-core-1.16.5-1.5.0_h1-alpha specifically

**Comment by josephtarbit** [comment]
Fixed
