### ISSUE TITLE
"Ticking memory connection" Crash

### ISSUE THREAD

**Issue by lartts** [nexusnode/crafting-dead#127]
Crash Report:
[crash-2021-06-17_22.37.37-server.txt](https://github.com/nexusnode/crafting-dead/files/6671477/crash-2021-06-17_22.37.37-server.txt)

Crash Log:
[2021-06-17-3.log](https://github.com/nexusnode/crafting-dead/files/6671483/2021-06-17-3.log)

Happens when loading a world that was just created

**Comment by josephtarbit** [comment]
Try with this: https://www.curseforge.com/minecraft/mc-mods/crafting-dead-immerse/files/3355284

**Comment by lartts** [comment]
Sadly, it still happens even when removing some mods

Crash Report:
[crash-2021-06-18_18.51.43-server.txt](https://github.com/nexusnode/crafting-dead/files/6676837/crash-2021-06-18_18.51.43-server.txt)

Crash Log:
[latest.log](https://github.com/nexusnode/crafting-dead/files/6676849/latest.log)

**Comment by josephtarbit** [comment]
Fixed

**Comment by josephtarbit** [comment]
Just released 1.7 which fixes this.
