### ISSUE TITLE
Crashing when loading world

### ISSUE THREAD

**Issue by Kurojime** [nexusnode/crafting-dead#128]
Crash Report
[crash-2021-06-20_14.44.34-server.txt](https://github.com/nexusnode/crafting-dead/files/6681850/crash-2021-06-20_14.44.34-server.txt)

Crash Log
[latest.log](https://github.com/nexusnode/crafting-dead/files/6681851/latest.log)

So far, tried to make new worlds but upon reaching 100, it crashes. Tried removing some mods but in the end, it only changes the crash report to write java.lang.IllegalStateException: Lock is no longer valid sometimes

**Comment by josephtarbit** [comment]
Duplicate of #127
