### ISSUE TITLE
1.16.5 Crash on generate world

### ISSUE THREAD

**Issue by BastardNeko** [nexusnode/crafting-dead#129]
The game crashes upon trying to generate a new world on latest patch.
[crash-2021-06-21_14.44.00-server.txt](https://github.com/nexusnode/crafting-dead/files/6688838/crash-2021-06-21_14.44.00-server.txt)

**Comment by MeMeiki** [comment]
I also have the same issue. Also if i try to make the mods unactive (on curseforge) it just says ¨failed to update installed enabled state¨

**Comment by josephtarbit** [comment]
Fixed in next update

**Comment by BastardNeko** [comment]
So when is the next update though,

**Comment by josephtarbit** [comment]
Soon - I suggest downgrading for the moment being.
