### ISSUE TITLE
Way to disable broken legs when taking no fall damage

### ISSUE THREAD

**Issue by BastardNeko** [nexusnode/crafting-dead#131]
I'm playing this mod with the origins mod, and I still get broken legs even when I don't take fall damage. The origins mod adds several different starts which give you different benefits and drawbacks, and the origin I choose to use negates fall damage. But even though I take no fall damage, I still brake my leg without fail. wtf

**Comment by josephtarbit** [comment]
Fixed: https://www.curseforge.com/minecraft/mc-mods/crafting-dead-survival/files/3368744
