### ISSUE TITLE
Removes Iron ingot smelting recipe

### ISSUE THREAD

**Issue by Sushant-Padha** [nexusnode/crafting-dead#132]
### SETUP
Using [crafting-dead-core-1.16.5-1.7.0-alpha.jar](https://www.curseforge.com/minecraft/mc-mods/crafting-dead/files/3363329) mod with [Forge 36.1.0](https://files.minecraftforge.net/net/minecraftforge/forge/index_1.16.5.html)
Trying to smelt up iron ore into iron ingots using a furnace.

### EXPECTED OUTCOME
Furnace: input iron ore in top slot, fuel in bottom slot and iron ingots are received after some time.
Blast Furnace: input iron ore in top slot, fuel in bottom slot and iron ingots are received after some time.

### ACTUAL OUTCOME
Furnace: input iron ore in top slot, fuel in bottom slot **BUT** no smelting takes place.
Blast Furnace: input iron ore in top slot, fuel in bottom slot and iron ingots are received after some time.

Smelting recipe of iron ore does not work in a furnace.

***NOTES:***
- [crafting-dead-core-1.16.5-1.7.0-alpha.jar](https://www.curseforge.com/minecraft/mc-mods/crafting-dead/files/3363329) is the latest available at the time of posting (*26/06/2021*)
- using older version [crafting-dead-core-1.16.5-1.6.1-alpha.jar](https://www.curseforge.com/minecraft/mc-mods/crafting-dead/files/3355282) crashes on "loading world" itself (as described in #127) so can't test this out

**Comment by Sm0keySa1m0n** [comment]
Fixed in next update
