### ISSUE TITLE
baby zombie nerf?

### ISSUE THREAD

**Issue by ilovecraftingdead** [nexusnode/crafting-dead#135]
going back on my original issue about baby zombies (#133), could you atleast nerf them to run at the same speed as the normal zombies would, especially the fast baby zombie please nerf that

**Comment by Herosilas** [comment]
I agree. Fast zombies and fast baby zombies make the experience less enjoyable.
Especially fast zombies with crazy high damage weapons that kill you in 1-2 quick hits even with the best protective gear (I'm looking at you, fast zombie with weaponized scythe!).
A way to disable these zombies would be greatly appreciated.

**Comment by josephtarbit** [comment]
Addressed in next update, their health and damage strength has been reduced.
