### ISSUE TITLE
[BUG] Not Firing Sometimes

### ISSUE THREAD

**Issue by lartts** [nexusnode/crafting-dead#139]
**Crafting Dead Version:** 
crafting-dead-core-1.16.5-1.7.2-alpha.jar

**Desc:**
Some semi-auto guns just can't shoot for a few seconds, guns that have full-auto, semi-auto, and burst are only able to shoot in full-auto. 

**Logs:**
The logs don't give any info at all about this specific problem.

**Comment by josephtarbit** [comment]
Could you show me a video of the problem?

**Comment by lartts** [comment]
Late but here:
https://drive.google.com/file/d/17sNIL3IVByGgxPjvni_doZYijZbA6niZ/view?usp=sharing

The shaking means I can't shoot
