### ISSUE TITLE
Reduce Zombie Spawning

### ISSUE THREAD

**Issue by BastardNeko** [nexusnode/crafting-dead#140]
Is there a way you could add a command or config option to reduce the crafting dead zombie spawning? I have a couple other mods that add overworld mobs and it feels like the massive amounts of cd zombies spawning in make it so these mods can't spawn in there stuff.

**Comment by josephtarbit** [comment]
This is what datapacks are for.

**Comment by BastardNeko** [comment]
Where would one find said datapack?

**Comment by josephtarbit** [comment]
You can make one with this: https://misode.github.io/

**Comment by BastardNeko** [comment]
I'm terribly sorry, but I can't even pretend to know how to use that. :/
