### ISSUE TITLE
[ Suggestion ] Dispenser (Vanilla Block)

### ISSUE THREAD

**Issue by Zensuyo** [nexusnode/crafting-dead#144]
I notice that if I load any kinds grenades on a dispenser it doesn't trigger/ignite to explode once it takes off. It just spit it out. This would be useful for traps and ambushes.

**Comment by 0xE69** [comment]
Can you confirm if this issue is still present on the latest 1.18.2 build?

**Comment by josephtarbit** [comment]
This is something that needs to be implemented by us (not a bug).

**Comment by 0xE69** [comment]
@juanmuscaria would you look to add a server-side configuration for this?
