### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by maxmahl** [nexusnode/crafting-dead#147]
Pastebin: https://pastebin.com/vwHdECYa

Hi,
I am trying to install the "PwrDown's Zombie Apocalypse" mod pack but when I try to convert it into a server it crashes. Could you maybe help me out?

Thanks in advance,
Max

**Comment by josephtarbit** [comment]
Use the latest Forge version for 1.16.5.

**Comment by josephtarbit** [comment]
Is this resolved?

**Comment by maxmahl** [comment]
Yes it is, Thanks! I updated the mod to a newer version.

**Comment by josephtarbit** [comment]
Glad to hear.
