### ISSUE TITLE
Plz Put Zombie drop into a json file!

### ISSUE THREAD

**Issue by momentforever** [nexusnode/crafting-dead#148]
## Verison

1.16.x crafting-dead-survival

## Why this problem

When I searched for the monster's drop profile, I didn't find the monster drop information and monster production switch of the mod in all the profiles.
When I browsed the source code, I found that it seemed that the monster drop was written into the code. So, should I store the mod’s monster generation, drop options, probability and other information in the configuration file?

## Suggestions on how to modify

rewrite crafting-dead/crafting-dead-survival/src/main/java/com/craftingdead/survival/data/loot/SupplyDropLootTables.java

**Comment by josephtarbit** [comment]
How is `SupplyDropLootTables` related to zombies?

**Comment by momentforever** [comment]
I guess it's this file, I'm not sure. Can you find the relevant configuration here?

**Comment by momentforever** [comment]
> How is `SupplyDropLootTables` related to zombies?

I guess it's this file, I'm not sure. Can you find the relevant configuration here?

**Comment by 0xE69** [comment]
We are now tracking this on our internal software 1201740156216648/1202082415027842

**Comment by josephtarbit** [comment]
This is achievable via datapacks.
