### ISSUE TITLE
[Suggestion & bugs] Disable the swap item for the guns

### ISSUE THREAD

**Issue by Zensuyo** [nexusnode/crafting-dead#151]
Disable the swap item which is (F) key when holding a gun or you're not able to put it in the inventory.  A small chat message will pop up on the hotbar you're both hands are occupied.

**Comment by 0xE69** [comment]
@Zensuyo Can you confirm if this is still an issue with the latest 1.18.2, If so we can create an internal tracker.

**Comment by Zensuyo** [comment]
Sure will test out the CD latest version

**Comment by Zensuyo** [comment]
Yes, still does on 1.18.2 juan have screenshot of those on <devops channel>

**Comment by josephtarbit** [comment]
Probably gonna need a mixin for this one.

**Comment by 0xE69** [comment]
@Sm0keySa1m0n Do you have an update on this?

**Comment by wumengzhixing** [comment]
That, my friend, is a very strange question.
Please disable the offhand which is sameone when holding a gun.
![1](https://user-images.githubusercontent.com/88496786/210962341-11f46e32-919e-40e7-a90c-ab99603e87f6.png)
