### ISSUE TITLE
Changing the death message

### ISSUE THREAD

**Issue by Arownic** [nexusnode/crafting-dead#152]
So I made a plugin and what it does is when the death message is "player was shot" and it sets it to _player_ killed player using item
but the player that's italic , being the attacker, does not show and the item gets what item the attacker is holding

so it returns as <none> as thats what its supposed to display when there is a error
![image](https://user-images.githubusercontent.com/67923888/138749703-9220136a-b68b-4beb-8304-b98ed9e31e57.png)

I need help with this as I can't figure out a way to fix this.

**Comment by josephtarbit** [comment]
Show your code

**Comment by Arownic** [comment]
![image](https://user-images.githubusercontent.com/67923888/138765350-f96bbe2e-6096-4e01-ac33-212294380d4a.png)
It does use the Skript plugin but if I do need to do anything java, I can

**Comment by josephtarbit** [comment]
Does it work for vanilla deaths?

**Comment by Arownic** [comment]
only the gun death doesn't work
![image](https://user-images.githubusercontent.com/67923888/138768428-62112bf8-7dcf-4d8b-9209-6e4d4e175884.png)
![image](https://user-images.githubusercontent.com/67923888/138768647-cb1db372-01ad-4122-8555-402e32c4b23e.png)
![image](https://user-images.githubusercontent.com/67923888/138768998-9c8e1b33-649f-44c9-a31f-8e79cc851b57.png)

**Comment by Arownic** [comment]
![image](https://user-images.githubusercontent.com/67923888/138769730-ff8d114c-fe82-46b2-94eb-c8a3d13439fa.png)
full code btw

**Comment by Arownic** [comment]
What would I need to import to make this work?

**Comment by josephtarbit** [comment]
I believe I have fixed this in the latest commit.
