### ISSUE TITLE
Gun Texture Missing On One Side?

### ISSUE THREAD

**Issue by Auto-Gear** [nexusnode/crafting-dead#154]
I realized that I put my bug report in the wrong spot.
My other one is in the comments on the mod page itself, but I guess I'll post it here as well in hopes of getting a quicker answer

Why are the outer sides of the weapons see through, as if the model wasn't finished.

I'm the type of person that loves getting cinematic shots and directing roleplays with mods like this, but its hard to do that when your only able to record one side of a character.

If there is a way to fix this, please let me know.

 

Here is an example image:
![2021-11-03_22 25 23](https://user-images.githubusercontent.com/93710542/140300006-3cf53b36-7393-4bae-8389-3063a9cfc2be.png)
![2021-11-03_22 25 43](https://user-images.githubusercontent.com/93710542/140300091-eeea6722-864d-4d35-a83a-73ca00bc89b6.png)

**Comment by josephtarbit** [comment]
This is a problem with the models, we're replacing all of them with new ones.
