### ISSUE TITLE
Some hits from guns do not register.

### ISSUE THREAD

**Issue by bS-ui** [nexusnode/crafting-dead#16]
As you can see in the video below, on the last zombie I killed, 6 total shots were fired but only 3 of those 6 registered as hits and did damage. It seems to be happening on every gun but I haven't tested each individually.

_(Video is inside of the ZIP, couldn't upload the MP4 itself)_
[2020-11-11 19-06-28.zip](https://github.com/nexusnode/crafting-dead/files/5527469/2020-11-11.19-06-28.zip)

This is also tested only on Zombies as seen in the video, not sure if it applies to players but still worth looking into and fixing :)

**Comment by josephtarbit** [comment]
Fixed in df4762b
