### ISSUE TITLE
Reply Mod Incompatibility

### ISSUE THREAD

**Issue by Arownic** [nexusnode/crafting-dead#163]
The Mod Crafting Dead Immerse breaks the Start/Stop Recording Buttons in the main menu, there is also no Record Server/World button when selecting a Official or Unofficial Server, you may also not record a singleplayer world with the Crafting Dead Immerse

If I remove the mod Crafting Dead Immerse, the problems go away.

**Comment by Arownic** [comment]
Singleplayer works. Sorry.

**Comment by 0xE69** [comment]
Closing down, Followed up with Arownic in DM's.
