### ISSUE TITLE
Cant download the modpack?

### ISSUE THREAD

**Issue by Elpximso** [nexusnode/crafting-dead#164]
Im trying to download the modpack from curseforge launcher, and i cant, i get a error each time. I even tried to download the pack as a folder from the website and then import it, but when doing that it says the zip file contains an invalid profile.

I have tried restarting curse serveral times.
I can download other modpacks

**Comment by josephtarbit** [comment]
Are you still experiencing this issue?

**Comment by Elpximso** [comment]
> Are you still experiencing this issue?

No i got it to work :D
