### ISSUE TITLE
Immerse Java Error

### ISSUE THREAD

**Issue by Arownic** [nexusnode/crafting-dead#166]
Hey, I've done some testing and Immerse 1.0.11 does not work on any other version then Java 8

could you fix this error as it breaks when its added on most server hosts, thanks!

**Comment by denireilly** [comment]
i beleve the mod has a requirement for this java version

**Comment by josephtarbit** [comment]
I’m aware of this although server hosts should be using Java 8 for anything below 1.17 as that’s what the game is compiled for and shipped with.

**Comment by Arownic** [comment]
most use java 17 or 11 for 1.18.1 and what not

**Comment by josephtarbit** [comment]
I know, we're talking about 1.16 though

**Comment by Arownic** [comment]
for example slimeservers uses java 16 even on 1.16.5

**Comment by Arownic** [comment]
theres others too

**Comment by Arownic** [comment]
and it also doesn't work with anything else but java 8 on clients

**Comment by Arownic** [comment]
this is a issue for people on multimc who haven't installed java 8 or haven't set the launcher to run it with java 8 and it makes it a hassle for basic users in that regard
