### ISSUE TITLE
difficulty increase

### ISSUE THREAD

**Issue by ilykoshechka** [nexusnode/crafting-dead#167]
sorry to bother you, but is there a way to cap the difficulty increase?

**Comment by josephtarbit** [comment]
What do you mean by difficulty increase?

**Comment by ilykoshechka** [comment]
> What do you mean by difficulty increase?

i mean how the difficulty in the top left corner progressively increases

**Comment by josephtarbit** [comment]
I don’t know what you’re taking about, can you show me a screenshot?
