### ISSUE TITLE
Minecraft original model glitch

### ISSUE THREAD

**Issue by Bigbang56** [nexusnode/crafting-dead#169]
So i installed the mod (only this) in Minecraft 1.16.5 and when i opened the game lots of textures of vanilla Minecraft were glitchy and the models looked ugly idk what caused this

**Comment by josephtarbit** [comment]
When you remove the mod does it fix the issue?

**Comment by Bigbang56** [comment]
> When you remove the mod does it fix the issue?

Yeah it does

**Comment by josephtarbit** [comment]
Can you upload screenshots of these texture & model glitches?

**Comment by josephtarbit** [comment]
Also, do you have optifine installed?

**Comment by Bigbang56** [comment]
> Can you upload screenshots of these texture & model glitches?

![Uploading Screenshot_2022-02-28-15-17-33-981_net.kdt.pojavlaunch.jpg…]()

**Comment by Bigbang56** [comment]
![Screenshot_2022-02-28-15-17-20-282_net kdt pojavlaunch](https://user-images.githubusercontent.com/100470720/155961609-2cef5ed2-b6d1-4bcb-8bba-3c1c2ca407d4.jpg)
![Uploading Screenshot_2022-02-28-15-16-26-492_net.kdt.pojavlaunch.jpg…]()

**Comment by Bigbang56** [comment]
> Also, do you have optifine installed?
Yeah I tried with optifine and vanilla and I'm using the Android version of Minecraft

**Comment by Bigbang56** [comment]
I fixed it! It was there because of mipmap settings I played around with them till i got the result i wanted but thank you so much for looking into this
