### ISSUE TITLE
The Gun Crosshair doesn't seem to matter.

### ISSUE THREAD

**Issue by bS-ui** [nexusnode/crafting-dead#17]
When shooting guns from the hip, the crosshair that appears and gets larger or smaller depending on how you move doesn't seem to matter at all. When you shoot it just hits the center dot and nothing in the surrounding area.

_(Video is inside of the ZIP, couldn't upload the MP4 itself)_
[2020-11-11 19-13-41.zip](https://github.com/nexusnode/crafting-dead/files/5527500/2020-11-11.19-13-41.zip)

Haven't tested with every single gun individually again but I'm pretty sure this applies to all guns.

**Comment by Afarion1** [comment]
1. https://github.com/nexusnode/crafting-dead/blob/86d09899273c7a7cd0e76833f9129237cad6feb6/crafting-dead-core/src/main/java/com/craftingdead/core/capability/gun/DefaultGun.java#L329
* 1.5F on that line makes the accuracy pretty much always perfect

2. https://github.com/nexusnode/crafting-dead/blob/86d09899273c7a7cd0e76833f9129237cad6feb6/crafting-dead-core/src/main/java/com/craftingdead/core/util/RayTraceUtil.java#L154-L160
This spread calculation seems very weird, maybe it's simpler to implement it using pitch/yaw?
At the very least look vector's values could become > 1 and < -1, which will probably lead to unexpected ray trace behavior.

**Comment by josephtarbit** [comment]
Fixed in 4879597
