### ISSUE TITLE
1.18.1 launch issue

### ISSUE THREAD

**Issue by F0rg0ttenK1ng** [nexusnode/crafting-dead#173]
The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Cannot invoke "com.craftingdead.core.CraftingDead.getClientDist()" because the return value of "com.craftingdead.core.CraftingDead.getInstance()" is null
Exit Code: -1

**Comment by Arownic** [comment]
any other mods?

**Comment by F0rg0ttenK1ng** [comment]
TenshiLib
Stoneholm
More Villagers
Human Companions
Guard Villagers
Crafting Dead Survival
Crafting Dead
Just Enough Items
InControl
Doggy Talents 2
Domum ornamentum 
Structurize 
Cloth Config v4 API
Improved mobs mod
Multi-Piston
MineColonies
Mob Sunscreen


A redownload of crafting dead fixed the issue and the game now launches

**Comment by robster20022002** [comment]
I'm having the same issue but for 1.18.2. a redownload did not work for me.

my mod list:
cityblocks 1.4.3 (Crafting dead addon)
controlling 1.18.2-9.0+17
coroutil-1.18.1-1.2.37
crafting-dead-core-1.18.2-1.7.6-alpha
crafting-dead-survival-1.18.2-1.1.9-alpha
create-mc1.18.2_v0.4.1
dynamiclights-1.18.6
DynamicTrees-1.18.2-0.11.0-Alpha1  (this might have something to do with it, if i remove this one it seems to work ok)
EpicFight-18.1.20-beta
flywheel-forge-1.18-062
immersive_weathering-1.18.2-1.0.6
jei-1.18.2-9.5.5.174
lostcities-1.18-5.1.1
(the following are macaws mods)
mcw-bridges-2.0.2-mc1.18.2
mcw-doors-1.0.6-mc1.18.2
mcw-fences-1.0.3-mc1.18.2
mcw-furniture-3.0.0-mc1.18.2
mcw-lights-1.0.3-mc1.18.2
mcw-roofs-2.1.1-mc1.18.2
mcw-trapdoors-1.0.5-mc1.18.2
mcw-windows-2.0.3-mc1.18.2
(end of macaws)
MmmMmmMmmMmm-1.18-1.5.1 (target dummy)
Serene+Seasons-1.18.2-7.0.0.13
ToolBelt-1.18.2-1.18.7
zombieawareness-1.18.2-1.12.3

one of the crash reports (doesn't have that mod list at the end which I'm guessing means the error occurred before the game began loading them)

[crash-2022-06-06_23.03.28-client.txt](https://github.com/nexusnode/crafting-dead/files/8848592/crash-2022-06-06_23.03.28-client.txt)

**Comment by Arownic** [comment]
try with just crafting dead core then add in crafting dead survival survival, if none of that works then try the newest version (check by date added not by version number)

**Comment by Arownic** [comment]
all the other mods + crafting dead core*

**Comment by robster20022002** [comment]
the issue remained with just core + other mods and with latest versions (May 12 2022)
