### ISSUE TITLE
The armor on Zombies have no effect.

### ISSUE THREAD

**Issue by bS-ui** [nexusnode/crafting-dead#18]
I tested guns on a couple of Zombies with a health bar mod and the Armor and Helmets on the zombies that naturally spawn have no effect/give 0 protection. 

**Armor**
_(Video is inside of the ZIP, couldn't upload the MP4 itself)_
[2020-11-11 19-32-53.zip](https://github.com/nexusnode/crafting-dead/files/5527540/2020-11-11.19-32-53.zip)

**Helmets**
_(Video is inside of the ZIP, couldn't upload the MP4 itself)_
[2020-11-11 19-37-48.zip](https://github.com/nexusnode/crafting-dead/files/5527543/2020-11-11.19-37-48.zip)

Again, I didn't use all weapons, could be this one specifically, could be the certain armors, not sure. But still worth looking in to unless this is intended.

**Comment by josephtarbit** [comment]
Are you referring to vanilla armour and helmets?

**Comment by bS-ui** [comment]
Nope, the CD Armor that the zombies now spawn with don't seem to give extra protection against guns.

**Comment by josephtarbit** [comment]
That’s intended, CD armour only protects against infection and bleeding.

**Comment by bS-ui** [comment]
Oh gotcha, so are players meant to be able to get items like Vanilla Armor this time around? Is that why all of the guns have recipes and whatnot?

**Comment by josephtarbit** [comment]
Precisely.
