### ISSUE TITLE
1.16.5 Dropped Items not Rendering

### ISSUE THREAD

**Issue by BastardNeko** [nexusnode/crafting-dead#186]
With Crafting Dead and Crafting Dead Survival installed in my modpack, dropped item entities are not visible, but still there. When I disable CD and CDS, and they are visible. I tried disabling other mods with CD and CDS enabled, and the issue is still present. Running latest versions of both mods for 1.16.5 (As of 4/11/2022) along with forge 36.2.20.

**Comment by 0xE69** [comment]
We are no longer supporting the 1.16.5 version, Please update to 1.18.2 which has patched many of the issues you are facing.

**Comment by BastardNeko** [comment]
Well that sucks. Can't update cause There are crucial mods in my modpack that are locked in 1.16.5 currently.

**Comment by 0xE69** [comment]
Would you be able to contact on discord? Brad#8888

**Comment by BastardNeko** [comment]
Yeah, my discord is BastardNeko#2455
