### ISSUE TITLE
Armor on Zombies disappear after they kill you (Visually).

### ISSUE THREAD

**Issue by bS-ui** [nexusnode/crafting-dead#19]
I noticed that when I was killed by a zombie with armor on and respawned, it didn't show it as wearing anything but once it was killed the armor still dropped.

_(Video is inside of the ZIP, couldn't upload the MP4 itself)_
[2020-11-11 19-47-22.zip](https://github.com/nexusnode/crafting-dead/files/5527566/2020-11-11.19-47-22.zip)

Not tested with every armor of course or every weapon and it might just be me. Always still worth looking into :)

EDIT: This seems to not be caused by the Zombie killing the player but the player dying in general. I killed myself around about 30 zombies and all of the armor they had disappeared. It seems to either be literally EVERY zombie or within a certain range.

_(Video is inside of the ZIP, couldn't upload the MP4 itself)_
[2020-11-11 19-56-49.zip](https://github.com/nexusnode/crafting-dead/files/5527587/2020-11-11.19-56-49.zip)

**Comment by josephtarbit** [comment]
Fixed by 13c1750
