### ISSUE TITLE
Issue with being killed while reloading

### ISSUE THREAD

**Issue by bS-ui** [nexusnode/crafting-dead#191]
I'm not sure if there is a proper format to these issues anymore or if there ever was but in the current version published on CurseForge for the 1.18.2 modpack, there is an issue with the way reloading is handled vs. how it was in 1.6.4. Since the magazine is not placed into your inventory until after you finish the reloading animation/sound, if you die during this reloading process, your magazine is lost. 

I can see that after I am dead, while still on the death screen, that the magazine is placed into my inventory as if I was still alive and then it is lost when I respawn.

Odd issue and not really a big one but it might inconvenience people if they die in the middle of reloading their gun while being attacked by a zombie horde, their old magazine is lost and now they cannot refill it.

**Comment by 0xE69** [comment]
The way reloading is handled can be configured in your client (for single player) or within the server configs (for multiplayer)

**Comment by josephtarbit** [comment]
Yeah that's a bug, needs to be fixed
