### ISSUE TITLE
Cannot invoke "com.craftingdead.core.CraftingDead.getClientDist()" because the return value is null

### ISSUE THREAD

**Issue by Mario-Beck** [nexusnode/crafting-dead#197]
Hello,

just wanted to notify you of a crash that keeps happening 100% of the time.

Background: i just made a new profile in the curseclient and randomly installed some mods i would like to play locally.
Since i added This mod the pack i had so far keeps crashing. Maybe other mods are at fault here, but i am not so good at reading error logs. The one thing that catched my eye was this mod. So i attached the full report.

> Description: Rendering overlay
> 
> java.lang.NullPointerException: Cannot invoke "com.craftingdead.core.CraftingDead.getClientDist()" because the return value of "com.craftingdead.core.CraftingDead.getInstance()" is null
> 	at net.minecraft.client.resources.model.ModelBakery.handler$zbe000$prepare(ModelBakery.java:692) ~[client-1.18.2-20220404.173914-srg.jar%23108!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:craftingdead.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.resources.model.ModelBakery.processLoading(ModelBakery.java:173) ~[client-1.18.2-20220404.173914-srg.jar%23108!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:craftingdead.mixins.json:ModelBakeryMixin,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraftforge.client.model.ForgeModelBakery.<init>(ForgeModelBakery.java:61) ~[forge-1.18.2-40.1.47-universal.jar%23113!/:?] {re:classloading}
> 	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:57) ~[client-1.18.2-20220404.173914-srg.jar%23108!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:quark.mixins.json:client.ModelManagerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.resources.model.ModelManager.m_5944_(ModelManager.java:20) ~[client-1.18.2-20220404.173914-srg.jar%23108!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:quark.mixins.json:client.ModelManagerMixin,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10786_(SimplePreparableReloadListener.java:11) ~[client-1.18.2-20220404.173914-srg.jar%23108!/:?] {re:classloading,re:mixin}
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?] {}
> 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
> 	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Render thread
> Stacktrace:
> 	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:882) ~[client-1.18.2-20220404.173914-srg.jar%23108!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:craftingdead.mixins.json:GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
> -- Overlay render details --
> Details:
> 	Overlay name: net.minecraft.client.gui.screens.LoadingOverlay
> Stacktrace:
> 	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:882) ~[client-1.18.2-20220404.173914-srg.jar%23108!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:craftingdead.mixins.json:GameRendererMixin,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1044) ~[client-1.18.2-20220404.173914-srg.jar%23108!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:enhancedvisuals.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:663) ~[client-1.18.2-20220404.173914-srg.jar%23108!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:enhancedvisuals.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23108!/:?] {re:classloading,pl:runtimedistcleaner:A}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
> 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
> 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.47.jar%2316!/:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
> 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
> 
> 
> -- Last reload --
> Details:
> 	Reload number: 1
> 	Reload reason: initial
> 	Finished: No
> 	Packs: Default
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.18.2
> 	Minecraft Version ID: 1.18.2
> 	Operating System: Windows 10 (amd64) version 10.0
> 	Java Version: 17.0.1, Microsoft
> 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
> 	Memory: 1868514168 bytes (1781 MiB) / 3292528640 bytes (3140 MiB) up to 8589934592 bytes (8192 MiB)
> 	CPUs: 12
> 	Processor Vendor: AuthenticAMD
> 	Processor Name: AMD Ryzen 5 3600X 6-Core Processor             
> 	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
> 	Microarchitecture: Zen 2
> 	Frequency (GHz): 3.79
> 	Number of physical packages: 1
> 	Number of physical CPUs: 6
> 	Number of logical CPUs: 12
> 	Graphics card #0 name: AMD Radeon RX 5700 XT
> 	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
> 	Graphics card #0 VRAM (MB): 4095.00
> 	Graphics card #0 deviceId: 0x731f
> 	Graphics card #0 versionInfo: DriverVersion=30.0.13023.4001
> 	Memory slot #0 capacity (MB): 16384.00
> 	Memory slot #0 clockSpeed (GHz): 3.20
> 	Memory slot #0 type: DDR4
> 	Memory slot #1 capacity (MB): 16384.00
> 	Memory slot #1 clockSpeed (GHz): 3.20
> 	Memory slot #1 type: DDR4
> 	Virtual memory max (MB): 37582.94
> 	Virtual memory used (MB): 24993.03
> 	Swap memory total (MB): 4864.00
> 	Swap memory used (MB): 267.89
> 	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8192m -Xms256m
> 	Launched Version: forge-40.1.47
> 	Backend library: LWJGL version 3.2.2 SNAPSHOT
> 	Backend API: AMD Radeon RX 5700 XT GL version 3.2.14761 Core Profile Forward-Compatible Context 21.30.23.04 30.0.13023.4001, ATI Technologies Inc.
> 	Window size: 1920x1061
> 	GL Caps: Using framebuffer using OpenGL 3.2
> 	GL debug messages: 
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'forge'
> 	Type: Client (map_client.txt)
> 	Graphics mode: fancy
> 	Resource Packs: 
> 	Current Language: English (US)
> 	CPU: 12x AMD Ryzen 5 3600X 6-Core Processor 
> 	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
> 	ModLauncher launch target: forgeclient
> 	ModLauncher naming: srg
> 	ModLauncher services: 
> 		 mixin PLUGINSERVICE 
> 		 eventbus PLUGINSERVICE 
> 		 slf4jfixer PLUGINSERVICE 
> 		 object_holder_definalize PLUGINSERVICE 
> 		 runtime_enum_extender PLUGINSERVICE 
> 		 capability_token_subclass PLUGINSERVICE 
> 		 accesstransformer PLUGINSERVICE 
> 		 runtimedistcleaner PLUGINSERVICE 
> 		 mixin TRANSFORMATIONSERVICE 
> 		 fml TRANSFORMATIONSERVICE 
> 	FML Language Providers: 
> 		minecraft@1.0
> 		lowcodefml@null
> 		javafml@null
> 	Mod List: 
> 		client-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |NONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
> 		forge-1.18.2-40.1.47-universal.jar                |Forge                         |forge                         |40.1.47             |NONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90

**Comment by josephtarbit** [comment]
Could you upload the log? (inside the logs folder)

**Comment by ZekerZhayard** [comment]
I have the same issue, here is the full log https://paste.ubuntu.com/p/5pNg7H9kQj/

**Comment by THFOL** [comment]
[minecraft-exported-crash-info-2022-06-16T16-50-33.zip](https://github.com/nexusnode/crafting-dead/files/8917265/minecraft-exported-crash-info-2022-06-16T16-50-33.zip)
This is my crash report

**Comment by josephtarbit** [comment]
> I have the same issue, here is the full log https://paste.ubuntu.com/p/5pNg7H9kQj/

Zeker, your issue is that you have createdeco in your mods folder when it's a fabric mod. (This causes FML not to load CD which means it's not present when getting accessed by a mixin causing a crash)

**Comment by THFOL** [comment]
[minecraft-exported-crash-info-2022-06-16T17-08-09.zip](https://github.com/nexusnode/crafting-dead/files/8917430/minecraft-exported-crash-info-2022-06-16T17-08-09.zip)
I tried to delete the wrong mod, but it still failed to start. This is a new error report

**Comment by THFOL** [comment]
> > 我有同样的问题，这里是完整的日志 https://paste.ubuntu.com/p/5pNg7H9kQj/
> 
> Zeker，你的问题是，当它是一个织物mod时，你已经在你的mods文件夹中创建了eco。（这导致FML不加载CD，这意味着当被导致崩溃的mixin访问时，它不存在）

I tried to delete the wrong mod, but it still failed to start. This is a new error report
[minecraft-exported-crash-info-2022-06-16T17-08-09.zip](https://github.com/nexusnode/crafting-dead/files/8918046/minecraft-exported-crash-info-2022-06-16T17-08-09.zip)

**Comment by josephtarbit** [comment]
I'm still seeing this in the log: `The Mod File D:\Download\.minecraft\versions\1.18.2\mods\createdeco-1.2.7a-fabric-1.18.2.jar has mods that were not found`

**Comment by THFOL** [comment]
[minecraft-exported-crash-info-2022-06-18T09-21-07.zip](https://github.com/nexusnode/crafting-dead/files/8932751/minecraft-exported-crash-info-2022-06-18T09-21-07.zip)
My game module crashed after it was updated. Help me

**Comment by josephtarbit** [comment]
> [minecraft-exported-crash-info-2022-06-18T09-21-07.zip](https://github.com/nexusnode/crafting-dead/files/8932751/minecraft-exported-crash-info-2022-06-18T09-21-07.zip) My game module crashed after it was updated. Help me

You need to use Java 17.

**Comment by THFOL** [comment]
[Uploading minecraft-exported-crash-info-2022-06-19T07-49-13.zip…]()
I installed java17 and the crash problem has been solved, but I can't create the world. This is my error report. I can't understand it(I am a fool)

**Comment by THFOL** [comment]
[minecraft-exported-crash-info-2022-06-20T16-58-55.zip](https://github.com/nexusnode/crafting-dead/files/8939137/minecraft-exported-crash-info-2022-06-20T16-58-55.zip)
My game can start but can't create a world. It crashes after prompting to save the world
