### ISSUE TITLE
Spray Paints for weapons don't actually apply to the model.

### ISSUE THREAD

**Issue by bS-ui** [nexusnode/crafting-dead#20]
Spray Paints for weapons don't seem to actually apply to the held model, the only paint that seems to have a visual effect is the "Multi Paint" but this is only to the icon in the inventory, not the model itself. It also isn't consumed when it is put into the slot and the gun is moved out of the attachment grid. Not sure if that's intended or not. 

_(Video is inside of the ZIP, couldn't upload the MP4 itself)_
[2020-11-11 20-07-20.zip](https://github.com/nexusnode/crafting-dead/files/5527621/2020-11-11.20-07-20.zip)

Again, not every weapon and paint were tested but I'm pretty sure it applies to them all :)

**Comment by josephtarbit** [comment]
Fixed in upcoming release.
