### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by BluetoothPrime** [nexusnode/crafting-dead#204]
![image](https://user-images.githubusercontent.com/107854776/174591321-b3a33f87-f807-41aa-a3b2-db8f0c184653.png)
It says there's an object named "p_20281_" which is null and it makes the game crash even before to start. can someone help me?

**Comment by josephtarbit** [comment]
Did you add "Skin Layers 3D" to the game?

**Comment by josephtarbit** [comment]
If you did then you can fix the issue by disabling "enableSkulls" in the config.
