### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by THFOL** [nexusnode/crafting-dead#205]
My game can't create a world. It will crash as soon as it is create
[minecraft-exported-crash-info-2022-06-21T07-53-23.zip](https://github.com/nexusnode/crafting-dead/files/8944701/minecraft-exported-crash-info-2022-06-21T07-53-23.zip)
d

**Comment by josephtarbit** [comment]
Looks like an issue with [Enigmatic Legacy](https://www.curseforge.com/minecraft/mc-mods/enigmatic-legacy), report it to them.
