### ISSUE TITLE
Clothing - Helmet and Bags Textures not loading in inventory or game when used with SEUS shaders

### ISSUE THREAD

**Issue by Lencier10** [nexusnode/crafting-dead#207]
The helmet and clothing textures dont load with SEUS shaders or even internal shaders. Only loads when shaders are off

**Comment by josephtarbit** [comment]
Unfortunately there's not much we can do about that because Optifine replaces a lot of internal code in Minecraft and is closed source so we cannot see what they're changing in order to support it.
