### ISSUE TITLE
游戏崩溃

### ISSUE THREAD

**Issue by THFOL** [nexusnode/crafting-dead#208]
I can't open the game and keep reporting error
[minecraft-exported-crash-info-2022-06-27T15-47-34.zip](https://github.com/nexusnode/crafting-dead/files/8989693/minecraft-exported-crash-info-2022-06-27T15-47-34.zip)
s

**Comment by Arownic** [comment]
Could you send the latest crash report in the crash-reports folder?

**Comment by THFOL** [comment]
> Could you send the latest crash report in the crash-reports folder?
[minecraft-exported-crash-info-2022-06-27T21-01-17.zip](https://github.com/nexusnode/crafting-dead/files/8992164/minecraft-exported-crash-info-2022-06-27T21-01-17.zip)

**Comment by Arownic** [comment]
your launcher seems to be having a issue with your java version

**Comment by THFOL** [comment]
> your launcher seems to be having a issue with your java version
In theory, I shouldn't, because I use java19. If it's not for module conflicts or other problems, I can't think that I will try to use java18 or 17 when I wake up. If it still doesn't work, I will upload my crash report.

**Comment by THFOL** [comment]
> your launcher seems to be having a issue with your java version
I tried to replace Java, but I still couldn't. this is my latest error report. I hope it can solve my problem
[minecraft-exported-crash-info-2022-06-28T06-41-27.zip](https://github.com/nexusnode/crafting-dead/files/8996038/minecraft-exported-crash-info-2022-06-28T06-41-27.zip)
