### ISSUE TITLE
The game crash cannot be opened

### ISSUE THREAD

**Issue by THFOL** [nexusnode/crafting-dead#210]
I can't open my game

1.18.2
java19
[minecraft-exported-crash-info-2022-06-29T13-08-24.zip](https://github.com/nexusnode/crafting-dead/files/9007438/minecraft-exported-crash-info-2022-06-29T13-08-24.zip)

**Comment by Arownic** [comment]
try disabling optifine

**Comment by THFOL** [comment]
Still not, the latest error report

> 尝试禁用奥替芬
[minecraft-exported-crash-info-2022-06-29T14-05-10.zip](https://github.com/nexusnode/crafting-dead/files/9007693/minecraft-exported-crash-info-2022-06-29T14-05-10.zip)

**Comment by THFOL** [comment]
Still not, the latest error report
> try disabling optifine
[minecraft-exported-crash-info-2022-06-29T14-05-10.zip](https://github.com/nexusnode/crafting-dead/files/9007700/minecraft-exported-crash-info-2022-06-29T14-05-10.zip)

**Comment by THFOL** [comment]
> try disabling optifine

How's it going? Do you see anything wrong

**Comment by THFOL** [comment]
[minecraft-exported-crash-info-2022-07-01T12-53-44.zip](https://github.com/nexusnode/crafting-dead/files/9025167/minecraft-exported-crash-info-2022-07-01T12-53-44.zip)

**Comment by josephtarbit** [comment]
This is not an issue with Crafting Dead, only use this issue tracker if you have confirmed that the issue still occurs with only Crafting Dead installed.
