### ISSUE TITLE
[Issue, 1.18.2] Crash on launch

### ISSUE THREAD

**Issue by HonzaVinCZ** [nexusnode/crafting-dead#213]
Having a crash on launch while running CD with some other mod. Due to ammount of mods I have added, I can't filter off which mod is the incompatible one.
[crash-2022-07-15_21.23.51-client.txt](https://github.com/nexusnode/crafting-dead/files/9123491/crash-2022-07-15_21.23.51-client.txt)

crafting-dead-core-1.18.2-1.7.6-alpha

**Comment by HonzaVinCZ** [comment]
Found problem: 
Happens with newer versions of Forge. 
Tested with:
- 40.1.60 - crash
- 40.1.57 - crash
- 40.1.51 - no crash

**Comment by 0xE69** [comment]
40.1.59 - Please post a log with and the latest build from curseforge.

**Comment by HonzaVinCZ** [comment]
Closing this issue, I can't reproduce it anymore.
