### ISSUE TITLE
Glitched and ugly Minecraft models

### ISSUE THREAD

**Issue by Bigbang56** [nexusnode/crafting-dead#216]
When I install this mod, all the original models are ugly and are glitched. Idk what causes this exactly but pls help

**Comment by 0xE69** [comment]
@Bigbang56 What version are you trying? the latest actions are experimental alpha versions.

**Comment by Bigbang56** [comment]
> @Bigbang56 What version are you trying? the latest actions are experimental alpha versions.

I'm currently using 1.16.5-1.7.5 idk if it's stable or not

**Comment by Bigbang56** [comment]
Also I'm playing minecraft on Android via pojavlauncher

**Comment by josephtarbit** [comment]
The 1.16 models are slightly glitchy due to the conversion processes from the 1.6.4 model format to the 1.16 model format. In the 1.18+ version of the mod we have brand new models so the problem is gone.

**Comment by Bigbang56** [comment]
> The 1.16 models are slightly glitchy due to the conversion processes from the 1.6.4 model format to the 1.16 model format. In the 1.18+ version of the mod we have brand new models so the problem is gone.

As I have a modpack installed made for 1.16.5 I can't switch to 1.18 yk. I'm using the mod with the modpack.

**Comment by Bigbang56** [comment]
![Uploading 155961609-2cef5ed2-b6d1-4bcb-8bba-3c1c2ca407d4.jpg…]()

**Comment by josephtarbit** [comment]
> Uploading 155961609-2cef5ed2-b6d1-4bcb-8bba-3c1c2ca407d4.jpg…

This link is broken.

**Comment by Bigbang56** [comment]
![Uploading 155961609-2cef5ed2-b6d1-4bcb-8bba-3c1c2ca407d4.jpg…]()

**Comment by 0xE69** [comment]
Hello, We are not currently supporting fixes for 1.16.5, Please update to 1.18.2
