### ISSUE TITLE
Cannot start game

### ISSUE THREAD

**Issue by BastardNeko** [nexusnode/crafting-dead#226]
I keep getting this exit code. :/ Crash log attached.

"The game crashed whilst rendering overlay
Error: java.lang.NullPointerException: Cannot invoke "com.craftingdead.core.CraftingDead.getClientDist()" because the return value of "com.craftingdead.core.CraftingDead.getInstance()" is null
Exit Code: -1"

[crash-2022-08-02_21.41.05-client.txt](https://github.com/nexusnode/crafting-dead/files/9247254/crash-2022-08-02_21.41.05-client.txt)

**Comment by josephtarbit** [comment]
Need the full startup log.

**Comment by BastardNeko** [comment]
Never mind, I don't know what I did differently, but it's working again.
