### ISSUE TITLE
Mod Loading Error

### ISSUE THREAD

**Issue by CodeRedFox** [nexusnode/crafting-dead#233]
When I tried to load the crafting dead mod around half way through loading the few mods I had installed it crashed and now it says
"Crafting Dead encountered an error during the common_sutup event phase java.lang.NoSuchMethodError: 'net.minecraftforge,registries.RegistryBuilder" and I have no idea how to fix this

**Comment by josephtarbit** [comment]
Make sure both Crafting Dead and Forge are updated.

**Comment by 0xE69** [comment]
Please re-open if you are still having issues.
