### ISSUE TITLE
[Feature Request] Add config option to allow specification of mob spawning

### ISSUE THREAD

**Issue by mikedattolo** [nexusnode/crafting-dead#236]
Hey, I was wondering if it is possible to add a new feature to the config of the mod and allow for the user to specify or allow certain mobs to still spawn in-game. Cause I think it would be nice for other mobs from different mods to be still spawnable in-game or even to just add another aspect of survival to the game with hunting animals or other mobs. Much appreciation for the work that's been done so far. Thank you for reading my request.

**Comment by josephtarbit** [comment]
Crafting Dead doesn't block other mobs from spawning.

**Comment by mikedattolo** [comment]
> Crafting Dead doesn't block other mobs from spawning.

sorry, I've been away from the mod for a while and didn't catch that, I used to play when the mod was only available in 1.6.4 and I'm trying to make a mod pack using the mod, and I'm developing an addon mod to use with it which adds tamable creatures to the game and I notice when playing as a test that mobs like pigs, chickens, cows and more weren't spawning naturally and I was wondering how I could make them actually spawn along with my mod creatures. Sorry I'm kinda of a noob to this so please be patient with me

**Comment by mikedattolo** [comment]
> > Crafting Dead doesn't block other mobs from spawning.
> 
> sorry, I've been away from the mod for a while and didn't catch that, I used to play when the mod was only available in 1.6.4 and I'm trying to make a mod pack using the mod, and I'm developing an addon mod to use with it which adds tamable creatures to the game and I notice when playing as a test that mobs like pigs, chickens, cows and more weren't spawning naturally and I was wondering how I could make them actually spawn along with my mod creatures. Sorry I'm kinda of a noob to this so please be patient with me

and also since I'm trying to do this in 1.16.5

**Comment by josephtarbit** [comment]
We don't support 1.16.5 anymore, update to 1.18.
