### ISSUE TITLE
Effects like broken bones and bleeding

### ISSUE THREAD

**Issue by maxvilt** [nexusnode/crafting-dead#238]
Hello, I'm using minecraft 1.16.5 and I really like your mod, but effects like broken bones and bleeding cause significant discomfort and errors. How can i turn off this effects? Answer me please.

**Comment by 0xE69** [comment]
@maxvilt 1.16.5 is unsupported now, Please try thee 1.18.2 version.

**Comment by 0xE69** [comment]
Hello, We are not currently supporting fixes for 1.16.5, Please update to 1.18.2
