### ISSUE TITLE
Prone/Laying Down Accuracy Issue

### ISSUE THREAD

**Issue by bS-ui** [nexusnode/crafting-dead#24]
I found that when you lay down as opposed to standing up or crouching, your shots go about a block up from where they are supposed to be shooting. In the video I shoot while standing up showing the guns accuracy normally and then while laying down and you can see that the bullets are pretty far off.

_(Video is inside of the ZIP, couldn't upload the MP4 itself)_
[2020-11-15 12-22-41.zip](https://github.com/nexusnode/crafting-dead/files/5542807/2020-11-15.12-22-41.zip)

It's tested with the M4 in the video but I tried with a few other weapons and it seems to be the case with them all.

**Comment by josephtarbit** [comment]
@Afarion1 It seems this issue only occurs if the trigger is held down. If you do single click shots, it hits the correct position. Even if I reduce the fire rate of a gun in order to mimic doing single click shots, the issue still occurs.
