### ISSUE TITLE
I want to advertise your Crafting Dead mod to MCBBS.

### ISSUE THREAD

**Issue by imnotyangjiu** [nexusnode/crafting-dead#244]
The Crafting Dead mod is nice and it helps me a lot!
I am a Chinese player and I like your mod "Crafting Dead".
Could you please allow me to translate your mod and advertise it to MCBBS?
MCBBS is the largest Minecraft forum in China.
You know not all of them are good at English, they can't read your post (Even with Google translator) they need a Chinese translator.
I'll NEVER claim it as mine and mark you as the author .
People in MCBBS can contact me for suggestion or reporting bugs in Chinese,and then I can contact you in English.
We can make this mod better and better together.
Thank you!Looking forward that you can make more and more good mods!!!!

**Comment by josephtarbit** [comment]
Are you on Discord? We can talk further there.

**Comment by imnotyangjiu** [comment]
I added your friend, please pass

**Comment by josephtarbit** [comment]
> I added your friend, please pass

Awesome, I'll close this issue.

**Comment by Annijang** [comment]
你好，请问你在bbs发过帖子吗？
这么久了，请问你有没有制作好语言文件，我这几天已经将1.18.2的本体、生存、沉浸、装饰的语言文件都做好了，如果您没有发帖的打算，那么我将会在mcbbs发布行尸走肉的帖子。
