### ISSUE TITLE
Loot crate refresh time issue

### ISSUE THREAD

**Issue by Agnis118** [nexusnode/crafting-dead#247]
In the last commit of Crafting Dead 1.16. You added a way to config the refresh time in ticks of loot crates in crafting survival. But i have try each version of the mod and encountered the same issue everytime. It's possible to reduce the refresh time of crates. But it's not working when i try to increase it. it apeared that even if in the config file the number seems good, the time doesn't seems to increase over 1000 ticks the default set. I don't know if it's bug or if i just do something bad but i hope you can fix that. Thanks :).

**Comment by josephtarbit** [comment]
This might be an issue with how vanilla schedules block ticks, I'm not too sure; however, we don't support 1.16 anymore so I encourage you to try 1.18.
