### ISSUE TITLE
Validation uses gun capability not from snapshot

### ISSUE THREAD

**Issue by Afarion1** [nexusnode/crafting-dead#26]
Probably can be abused by quickly switching weapons
https://github.com/nexusnode/crafting-dead/blob/1641f1628df5f704c60344e9ae6170f2e25ce0c0/crafting-dead-core/src/main/java/com/craftingdead/core/network/message/play/ValidateLivingHitMessage.java#L55-L69

**Comment by josephtarbit** [comment]
That's why I do a trigger pressed check in the validate method to ensure they are actually shooting with that gun.

**Comment by Afarion1** [comment]
Then some shots will not register, especially if a player has high latency?

**Comment by josephtarbit** [comment]
That's true, goes back to what you said about validation packets being buffered. I'll clean the system up.

**Comment by josephtarbit** [comment]
This should be fine as the hit packet will still be in the correct order as it comes from the same client as the change weapon packet.
In addition, I've reduced the packet interval for hit validations.
