### ISSUE TITLE
Issue Report - Unavailable Link (502 Bad Gateway) When Attempting Project Build

### ISSUE THREAD

**Issue by deadmau5v** [nexusnode/crafting-dead#260]
I hope this message finds you well. I am writing to inform you of an issue I encountered while trying to build the project. Unfortunately, the following link has become unresponsive, leading to a 502 Bad Gateway error :(

### Link
https://maven.tarbits.co.uk/
`buildSrc/build.gradle`

### Error Message
```
Could not HEAD 'https://maven.tarbits.co.uk/releases/cpw/mods/bootstraplauncher/1.0.0/bootstraplauncher-1.0.0.pom'. Received status code 502 from the server: Bad Gateway
```

If there is an alternative link available or if you have any updates on this matter, I would greatly appreciate your input. Your swift attention to this matter would be of immense help.

Thank you for your time and consideration.

**Comment by josephtarbit** [comment]
I'll look into getting this fixed in the next day or two. Most likely an expired certificate.

**Comment by 0xE69** [comment]
We need to internally host this at craftingdead.net.

**Comment by josephtarbit** [comment]
Sorry forgot about this, it's fixed now.
