### ISSUE TITLE
Crafting Dead Legacy Crash on Start UP windows 11

### ISSUE THREAD

**Issue by NildsonWitcher** [nexusnode/crafting-dead#299]
Hello, I have a problem starting Minecraft with the crafting Dead 1.6.4 mod of the Minecraft version. I start it, the Mojang screen appears for a few seconds and then crashes. I don't know why. When using Windows 10 it works. but now I move to windows 11 and I'm having this problem. I've already tested Java and it's no problem. and I've already tested other mods other than Crafting Dead and everything went normally. only crafting dead causes this error. sorry for my horrible english.

**Comment by NildsonWitcher** [comment]
[crash-2024-10-09_21.21.02-client.txt](https://github.com/user-attachments/files/17321965/crash-2024-10-09_21.21.02-client.txt)
here is the crashlog with multimc


[crash-2024-10-09_20.05.08-client.txt](https://github.com/user-attachments/files/17322050/crash-2024-10-09_20.05.08-client.txt)
Here with CurseForge

**Comment by Zuki-777** [comment]
It seems that there was a problem with the Crafting Dead Mod 1.6.4 yesterday. I also encountered the same error. 
On October 8, I could launch the game fine. On October 9, I encountered this problem.

**Comment by NildsonWitcher** [comment]
> It seems that there was a problem with the Crafting Dead Mod 1.6.4 yesterday. I also encountered the same error. On October 8, I could launch the game fine. On October 9, I encountered this problem.

sad.   What happened to make the mod stop working? It's funny that I've had this mod saved for several years and nothing has ever happened. but suddenly the mod stops working. I don't understand much about Java, but I studied Java programming a little and I understand that it is a programming language that uses a lot of repositories/libraries from other places. but what stays in my head is, what happened? Lmao. I hope it fixes quickly because I love this mod and I want to play the legacy version again

**Comment by Zuki-777** [comment]
idk, my friend was checking the code and he said it might be the "var2 = com.craftingdead.k.e.a(var3)" in the code that caused the problem.

**Comment by Zuki-777** [comment]
> > It seems that there was a problem with the Crafting Dead Mod 1.6.4 yesterday. I also encountered the same error. On October 8, I could launch the game fine. On October 9, I encountered this problem.
> 
> sad. What happened to make the mod stop working? It's funny that I've had this mod saved for several years and nothing has ever happened. but suddenly the mod stops working. I don't understand much about Java, but I studied Java programming a little and I understand that it is a programming language that uses a lot of repositories/libraries from other places. but what stays in my head is, what happened? Lmao. I hope it fixes quickly because I love this mod and I want to play the legacy version again

idk, my friend was checking the code and he said it might be the "var2 = com.craftingdead.k.e.a(var3)" in the code that caused the problem.

**Comment by NildsonWitcher** [comment]
> > > It seems that there was a problem with the Crafting Dead Mod 1.6.4 yesterday. I also encountered the same error. On October 8, I could launch the game fine. On October 9, I encountered this problem.
> > 
> > 
> > sad. What happened to make the mod stop working? It's funny that I've had this mod saved for several years and nothing has ever happened. but suddenly the mod stops working. I don't understand much about Java, but I studied Java programming a little and I understand that it is a programming language that uses a lot of repositories/libraries from other places. but what stays in my head is, what happened? Lmao. I hope it fixes quickly because I love this mod and I want to play the legacy version again
> 
> idk, my friend was checking the code and he said it might be the "var2 = com.craftingdead.k.e.a(var3)" in the code that caused the problem.

sad, what's left for us to do is just wait. thanks

**Comment by Zuki-777** [comment]
> > It seems that there was a problem with the Crafting Dead Mod 1.6.4 yesterday. I also encountered the same error. On October 8, I could launch the game fine. On October 9, I encountered this problem.
> 
> sad. What happened to make the mod stop working? It's funny that I've had this mod saved for several years and nothing has ever happened. but suddenly the mod stops working. I don't understand much about Java, but I studied Java programming a little and I understand that it is a programming language that uses a lot of repositories/libraries from other places. but what stays in my head is, what happened? Lmao. I hope it fixes quickly because I love this mod and I want to play the legacy version again

It seems that the MOD will go to the Crafting Dead‘s server to download the configuration file during the startup phase, but there is a problem with the server, which makes it impossible to download the configuration file, which leads to a series of problems. 
We need "craftingdead.json".

**Comment by NildsonWitcher** [comment]
> > > It seems that there was a problem with the Crafting Dead Mod 1.6.4 yesterday. I also encountered the same error. On October 8, I could launch the game fine. On October 9, I encountered this problem.
> > 
> > 
> > sad. What happened to make the mod stop working? It's funny that I've had this mod saved for several years and nothing has ever happened. but suddenly the mod stops working. I don't understand much about Java, but I studied Java programming a little and I understand that it is a programming language that uses a lot of repositories/libraries from other places. but what stays in my head is, what happened? Lmao. I hope it fixes quickly because I love this mod and I want to play the legacy version again
> 
> It seems that the MOD will go to the Crafting Dead‘s server to download the configuration file during the startup phase, but there is a problem with the server, which makes it impossible to download the configuration file, which leads to a series of problems. We need "craftingdead.json".

wow, this is interesting. if you get the file and work please share and notify.

**Comment by Zuki-777** [comment]
> > > > It seems that there was a problem with the Crafting Dead Mod 1.6.4 yesterday. I also encountered the same error. On October 8, I could launch the game fine. On October 9, I encountered this problem.
> > > 
> > > 
> > > sad. What happened to make the mod stop working? It's funny that I've had this mod saved for several years and nothing has ever happened. but suddenly the mod stops working. I don't understand much about Java, but I studied Java programming a little and I understand that it is a programming language that uses a lot of repositories/libraries from other places. but what stays in my head is, what happened? Lmao. I hope it fixes quickly because I love this mod and I want to play the legacy version again
> > 
> > 
> > It seems that the MOD will go to the Crafting Dead‘s server to download the configuration file during the startup phase, but there is a problem with the server, which makes it impossible to download the configuration file, which leads to a series of problems. We need "craftingdead.json".
> 
> wow, this is interesting. if you get the file and work please share and notify.

According to the information provided by my friend,, we need to wait for the official download server to be reopened.  :(
But if you don't need the official server, you can create a json file yourself. Just now, I was able to open the game normally with the help of my friend.

**Comment by NildsonWitcher** [comment]
> > > > > Parece que houve um problema com o Crafting Dead Mod 1.6.4 ontem. Eu também encontrei o mesmo erro. Em 8 de outubro, eu consegui iniciar o jogo normalmente. Em 9 de outubro, eu encontrei esse problema.
> > > > 
> > > > 
> > > > triste. O que aconteceu para o mod parar de funcionar? É engraçado que eu tenho esse mod salvo há vários anos e nada nunca aconteceu. mas de repente o mod para de funcionar. Eu não entendo muito de Java, mas estudei um pouco de programação Java e entendo que é uma linguagem de programação que usa muitos repositórios/bibliotecas de outros lugares. mas o que fica na minha cabeça é, o que aconteceu? Kkkk. Espero que conserte rápido porque eu amo esse mod e quero jogar a versão legacy novamente
> > > 
> > > 
> > > Parece que o MOD irá para o servidor do Crafting Dead para baixar o arquivo de configuração durante a fase de inicialização, mas há um problema com o servidor, o que torna impossível baixar o arquivo de configuração, o que leva a uma série de problemas. Precisamos de "craftingdead.json".
> > 
> > 
> > Uau, isso é interessante. Se você conseguir o arquivo e o trabalho, por favor, compartilhe e notifique.
> 
> De acordo com as informações fornecidas pelo meu amigo, precisamos esperar o servidor oficial de download ser reaberto. :( Mas se você não precisa do servidor oficial, você pode criar um arquivo json você mesmo. Agora mesmo, consegui abrir o jogo normalmente com a ajuda do meu amigo.

Do I really create an empty json file? Or do I need to add something? If you can upload it here I will be eternally grateful. and where can I put the file?

**Comment by Zuki-777** [comment]
> > > > > > Parece que houve um problema com o Crafting Dead Mod 1.6.4 ontem. Eu também encontrei o mesmo erro. Em 8 de outubro, eu consegui iniciar o jogo normalmente. Em 9 de outubro, eu encontrei esse problema.
> > > > > 
> > > > > 
> > > > > triste. O que aconteceu para o mod parar de funcionar? É engraçado que eu tenho esse mod salvo há vários anos e nada nunca aconteceu. mas de repente o mod para de funcionar. Eu não entendo muito de Java, mas estudei um pouco de programação Java e entendo que é uma linguagem de programação que usa muitos repositórios/bibliotecas de outros lugares. mas o que fica na minha cabeça é, o que aconteceu? Kkkk. Espero que conserte rápido porque eu amo esse mod e quero jogar a versão legacy novamente
> > > > 
> > > > 
> > > > Parece que o MOD irá para o servidor do Crafting Dead para baixar o arquivo de configuração durante a fase de inicialização, mas há um problema com o servidor, o que torna impossível baixar o arquivo de configuração, o que leva a uma série de problemas. Precisamos de "craftingdead.json".
> > > 
> > > 
> > > Uau, isso é interessante. Se você conseguir o arquivo e o trabalho, por favor, compartilhe e notifique.
> > 
> > 
> > De acordo com as informações fornecidas pelo meu amigo, precisamos esperar o servidor oficial de download ser reaberto. :( Mas se você não precisa do servidor oficial, você pode criar um arquivo json você mesmo. Agora mesmo, consegui abrir o jogo normalmente com a ajuda do meu amigo.
> 
> Do I really create an empty json file? Or do I need to add something? If you can upload it here I will be eternally grateful. and where can I put the file?

Put it in the craftingdead folder. This folder is together with the mod and save folders
[craftingdead.json](https://github.com/user-attachments/files/17330840/craftingdead.json)
This is just a temporary measure. If the official download server is reopened, I still recommend using the official json file. 
You can find the official json file in the github

**Comment by NildsonWitcher** [comment]
> > > > > > > Parece que houve um problema com o Crafting Dead Mod 1.6.4 ontem. Eu também encontrei o mesmo erro. Em 8 de outubro, eu consegui iniciar o jogo normalmente. Em 9 de outubro, eu encontrei esse problema.
> > > > > > 
> > > > > > 
> > > > > > triste. O que aconteceu para o mod parar de funcionar? É engraçado que eu tenho esse mod salvo há vários anos e nada nunca aconteceu. mas de repente o mod para de funcionar. Eu não entendo muito de Java, mas estudei um pouco de programação Java e entendo que é uma linguagem de programação que usa muitos repositórios/bibliotecas de outros lugares. mas o que fica na minha cabeça é, o que aconteceu? Kkkk. Espero que conserte rápido porque eu amo esse mod e quero jogar a versão legacy novamente
> > > > > 
> > > > > 
> > > > > Parece que o MOD irá para o servidor do Crafting Dead para baixar o arquivo de configuração durante a fase de inicialização, mas há um problema com o servidor, o que torna impossível baixar o arquivo de configuração, o que leva a uma série de problemas. Precisamos de "craftingdead.json".
> > > > 
> > > > 
> > > > Uau, isso é interessante. Se você conseguir o arquivo e o trabalho, por favor, compartilhe e notifique.
> > > 
> > > 
> > > De acordo com as informações fornecidas pelo meu amigo, precisamos esperar o servidor oficial de download ser reaberto. :( Mas se você não precisa do servidor oficial, você pode criar um arquivo json você mesmo. Agora mesmo, consegui abrir o jogo normalmente com a ajuda do meu amigo.
> > 
> > 
> > Do I really create an empty json file? Or do I need to add something? If you can upload it here I will be eternally grateful. and where can I put the file?
> 
> Put it in the craftingdead folder. This folder is together with the mod and save folders [craftingdead.json](https://github.com/user-attachments/files/17330840/craftingdead.json) This is just a temporary measure. If the official download server is restored, I still recommend using the official json file. You can find the official json file in the github

okay, it worked. I noticed that it keeps trying to download "craftingdead.zip" but i see the download in the github. but otherwise it's normal. thank you very much.

**Comment by NildsonWitcher** [comment]
I will leave this topic open to help other people with the same problem until it is resolved. thanks Zuki-777 and your friend for the temporary solution

**Comment by NildsonWitcher** [comment]
> > > > > > > Parece que houve um problema com o Crafting Dead Mod 1.6.4 ontem. Eu também encontrei o mesmo erro. Em 8 de outubro, eu consegui iniciar o jogo normalmente. Em 9 de outubro, eu encontrei esse problema.
> > > > > > 
> > > > > > 
> > > > > > triste. O que aconteceu para o mod parar de funcionar? É engraçado que eu tenho esse mod salvo há vários anos e nada nunca aconteceu. mas de repente o mod para de funcionar. Eu não entendo muito de Java, mas estudei um pouco de programação Java e entendo que é uma linguagem de programação que usa muitos repositórios/bibliotecas de outros lugares. mas o que fica na minha cabeça é, o que aconteceu? Kkkk. Espero que conserte rápido porque eu amo esse mod e quero jogar a versão legacy novamente
> > > > > 
> > > > > 
> > > > > Parece que o MOD irá para o servidor do Crafting Dead para baixar o arquivo de configuração durante a fase de inicialização, mas há um problema com o servidor, o que torna impossível baixar o arquivo de configuração, o que leva a uma série de problemas. Precisamos de "craftingdead.json".
> > > > 
> > > > 
> > > > Uau, isso é interessante. Se você conseguir o arquivo e o trabalho, por favor, compartilhe e notifique.
> > > 
> > > 
> > > De acordo com as informações fornecidas pelo meu amigo, precisamos esperar o servidor oficial de download ser reaberto. :( Mas se você não precisa do servidor oficial, você pode criar um arquivo json você mesmo. Agora mesmo, consegui abrir o jogo normalmente com a ajuda do meu amigo.
> > 
> > 
> > Do I really create an empty json file? Or do I need to add something? If you can upload it here I will be eternally grateful. and where can I put the file?
> 
> Put it in the craftingdead folder. This folder is together with the mod and save folders [craftingdead.json](https://github.com/user-attachments/files/17330840/craftingdead.json) This is just a temporary measure. If the official download server is reopened, I still recommend using the official json file. You can find the official json file in the github

zuki, the problem has returned. I noticed that every time the game opens and replaces "craftingdead.json" it crashes again. I turned off my internet and opened the game with the old "craftingdead.json" and it starts normally. what is happening now is that it is overwriting the json file

**Comment by Zuki-777** [comment]
> > > > > > > > Parece que houve um problema com o Crafting Dead Mod 1.6.4 ontem. Eu também encontrei o mesmo erro. Em 8 de outubro, eu consegui iniciar o jogo normalmente. Em 9 de outubro, eu encontrei esse problema.
> > > > > > > 
> > > > > > > 
> > > > > > > triste. O que aconteceu para o mod parar de funcionar? É engraçado que eu tenho esse mod salvo há vários anos e nada nunca aconteceu. mas de repente o mod para de funcionar. Eu não entendo muito de Java, mas estudei um pouco de programação Java e entendo que é uma linguagem de programação que usa muitos repositórios/bibliotecas de outros lugares. mas o que fica na minha cabeça é, o que aconteceu? Kkkk. Espero que conserte rápido porque eu amo esse mod e quero jogar a versão legacy novamente
> > > > > > 
> > > > > > 
> > > > > > Parece que o MOD irá para o servidor do Crafting Dead para baixar o arquivo de configuração durante a fase de inicialização, mas há um problema com o servidor, o que torna impossível baixar o arquivo de configuração, o que leva a uma série de problemas. Precisamos de "craftingdead.json".
> > > > > 
> > > > > 
> > > > > Uau, isso é interessante. Se você conseguir o arquivo e o trabalho, por favor, compartilhe e notifique.
> > > > 
> > > > 
> > > > De acordo com as informações fornecidas pelo meu amigo, precisamos esperar o servidor oficial de download ser reaberto. :( Mas se você não precisa do servidor oficial, você pode criar um arquivo json você mesmo. Agora mesmo, consegui abrir o jogo normalmente com a ajuda do meu amigo.
> > > 
> > > 
> > > Do I really create an empty json file? Or do I need to add something? If you can upload it here I will be eternally grateful. and where can I put the file?
> > 
> > 
> > Put it in the craftingdead folder. This folder is together with the mod and save folders [craftingdead.json](https://github.com/user-attachments/files/17330840/craftingdead.json) This is just a temporary measure. If the official download server is reopened, I still recommend using the official json file. You can find the official json file in the github
> 
> zuki, the problem has returned. I noticed that every time the game opens and replaces "craftingdead.json" it crashes again. I turned off my internet and opened the game with the old "craftingdead.json" and it starts normally. what is happening now is that it is overwriting the json file

Bad news... but there's nothing I can do now.
Sorry :(

**Comment by NildsonWitcher** [comment]
> > > > > > > > > Parece que houve um problema com o Crafting Dead Mod 1.6.4 ontem. Eu também encontrei o mesmo erro. Em 8 de outubro, eu consegui iniciar o jogo normalmente. Em 9 de outubro, eu encontrei esse problema.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > triste. O que aconteceu para o mod parar de funcionar? É engraçado que eu tenho esse mod salvo há vários anos e nada nunca aconteceu. mas de repente o mod para de funcionar. Eu não entendo muito de Java, mas estudei um pouco de programação Java e entendo que é uma linguagem de programação que usa muitos repositórios/bibliotecas de outros lugares. mas o que fica na minha cabeça é, o que aconteceu? Kkkk. Espero que conserte rápido porque eu amo esse mod e quero jogar a versão legacy novamente
> > > > > > > 
> > > > > > > 
> > > > > > > Parece que o MOD irá para o servidor do Crafting Dead para baixar o arquivo de configuração durante a fase de inicialização, mas há um problema com o servidor, o que torna impossível baixar o arquivo de configuração, o que leva a uma série de problemas. Precisamos de "craftingdead.json".
> > > > > > 
> > > > > > 
> > > > > > Uau, isso é interessante. Se você conseguir o arquivo e o trabalho, por favor, compartilhe e notifique.
> > > > > 
> > > > > 
> > > > > De acordo com as informações fornecidas pelo meu amigo, precisamos esperar o servidor oficial de download ser reaberto. :( Mas se você não precisa do servidor oficial, você pode criar um arquivo json você mesmo. Agora mesmo, consegui abrir o jogo normalmente com a ajuda do meu amigo.
> > > > 
> > > > 
> > > > Do I really create an empty json file? Or do I need to add something? If you can upload it here I will be eternally grateful. and where can I put the file?
> > > 
> > > 
> > > Put it in the craftingdead folder. This folder is together with the mod and save folders [craftingdead.json](https://github.com/user-attachments/files/17330840/craftingdead.json) This is just a temporary measure. If the official download server is reopened, I still recommend using the official json file. You can find the official json file in the github
> > 
> > 
> > zuki, the problem has returned. I noticed that every time the game opens and replaces "craftingdead.json" it crashes again. I turned off my internet and opened the game with the old "craftingdead.json" and it starts normally. what is happening now is that it is overwriting the json file
> 
> Bad news... but there's nothing I can do now. Sorry :(

sad, thanks anyway

**Comment by 0xE69** [comment]
Hello, Closing this as it is related to 1.6.4 versions. 

However i can say that the issue was fixed yesterday. @NildsonWitcher @Zuki-777
