### ISSUE TITLE
Medi Pack

### ISSUE THREAD

**Issue by Sm0keySa1m0n** [nexusnode/crafting-dead#3]
Bandages and First Aid Kits can be used to create an item called medipack in the Crafting Menu.

The recipe requires 10 bandages and 1 First Aid Kit and 1 morphine

Medipacks can be used to stop ALL forms of issues such as bleeding, hunger and water levels – can be used while moving

Very effective to use these while being chased by a player or if you get shot while a First Aid Kit is active.

Note: It’s always more effective to use a bandage before using a first aid kit. The bandage will provide healing while you’re applying your first aid kit and save some health.

You can use your first aid kit while looting to save yourself time and health.

**Comment by bS-ui** [comment]
Not sure if this is a typo but how would we manage to fit 12 items into a crafting grid? Good idea though, being able to use a healing item while moving would be very valuable.
