### ISSUE TITLE
Issue when start a dedicated server.

### ISSUE THREAD

**Issue by Kopla-BR** [nexusnode/crafting-dead#40]
**Used Mod Version**: crafting-dead-core-1.16.4-1.1.1-alpha.jar
**Error LOG**: https://pastebin.com/iek09mzQ

PS: *[11:59:26] [main/FATAL] [net.minecraftforge.fml.server.ServerModLoader/]: Crash report saved to .\crash-reports\crash-2020-12-06_11.59.26-fml.txt* - Server doesn't start and it crash.

**Comment by josephtarbit** [comment]
Fixed.
