### ISSUE TITLE
Server soft bans players with awps (and maybe other guns) in their inventory.

### ISSUE THREAD

**Issue by Hallzmine** [nexusnode/crafting-dead#41]
I connected to my server to test out crafting dead on it (latest version just the core) I dragged an awp into my inventory from the creative inventory and it is now kicking me any time I try to connect with the following error message being displayed in console and it displaying Internal server error on my screen

[https://hastebin.com/xofoqurahe.properties](url)

**Comment by Hallzmine** [comment]
Quick update, ammo and other items seem to work, it is only when you hold a gun.

**Comment by Hallzmine** [comment]
If an entity, like a giant zombie, is holding a gun it will crash the server instead of soft banning the players.

**Comment by josephtarbit** [comment]
Is this 1.15 or 1.16?

**Comment by Hallzmine** [comment]
1.16.4 alpha 1.1.1
Built from the lastest commit

**Comment by josephtarbit** [comment]
I’ll look into it

**Comment by josephtarbit** [comment]
Fixed
