### ISSUE TITLE
Hit Reg is super inconsistent and feels terrible

### ISSUE THREAD

**Issue by Hallzmine** [nexusnode/crafting-dead#46]
https://youtu.be/Z00HThUciwY
The hit registration on certain guns seems to be super off, as you can see this pig is either bulletproof or  none of my shots are registering even though the blood particle is displaying. Also the AWP seems a little bit inaccurate. Previously I had unloaded several magazines with the iron sights and a 8x scope on a pig from 30~40 blocks and it displayed no particles and it didn't die.

**Comment by josephtarbit** [comment]
I can't recreate this issue. Occasionally shots won't hit because of a guns accuracy but apart from that it's not anywhere near as bad as you're having it.

**Comment by josephtarbit** [comment]
Closing until others comment on this issue.
