### ISSUE TITLE
Automatic guns only work in creative.

### ISSUE THREAD

**Issue by Hallzmine** [nexusnode/crafting-dead#58]
If you are in survival or adventure and hold down left click with any automatic or burst gun it will only fire one bullet, that does not do damage, and drain the magazine until you let go. I have tested this on both singleplayer and multiplayer, it doesn't work as intended on either.

**Comment by josephtarbit** [comment]
Fixed by 96003f7e1e3e69c5c2215f0aae3f610195860a18
