### ISSUE TITLE
Null point exception when player-entity respawn

### ISSUE THREAD

**Issue by Kopla-BR** [nexusnode/crafting-dead#6]
It was detected when I was testing the modpack in **version** 0.0.4 alpha.

- When the player's entity respawn after a death:

> **Stack-trace warn**: "**Missing living capability**";
> **Light error-line**: "at com.craftingdead.core.capability.living.Player.lambda$get$4(Player.java:271) ~[?:0.0.4-alpha] {re:classloading}";
> **Full error stack-trace**: https://pastebin.com/S1MMA5Pv;
> **Full client log**:  https://pastebin.com/UxiTSF15;

I was using **forge-31.2.45** to run it and Optifine for better rendering performance.
(This happened **even without** using Optifine)

**Comment by Kopla-BR** [comment]
PS: I don't know how to fix it by myself, i'm not familiarized with Forge > 1.15.x-1.16.x data-storage system.

**Maybe this post can help**: https://mcforge.readthedocs.io/en/1.15.x/datastorage/capabilities/#persisting-across-player-deaths

**Comment by josephtarbit** [comment]
This is a known issue, it's going to be fixed as part of a rewrite of some of the mod's internals.
