### ISSUE TITLE
server crashed

### ISSUE THREAD

**Issue by TSaltedfishKing** [nexusnode/crafting-dead#65]
crafting-dead-core-1.16.4-1.2.5-alpha
[crash-2021-01-27_18.36.57-fml.txt](https://github.com/nexusnode/crafting-dead/files/5879657/crash-2021-01-27_18.36.57-fml.txt)
[latest.log](https://github.com/nexusnode/crafting-dead/files/5879658/latest.log)

**Comment by josephtarbit** [comment]
Your forge version is out of date.

**Comment by josephtarbit** [comment]
Use this version: https://github.com/IzzelAliz/Arclight/releases/tag/1.16%2F1.0.11

**Comment by TSaltedfishKing** [comment]
OK，thank you
