### ISSUE TITLE
What's the meaning of this?

### ISSUE THREAD

**Issue by TSaltedfishKing** [nexusnode/crafting-dead#69]
I'm translating it, but I have some problems
at en_us.json
```
....
"action.preformer":" Performer:%1$s"
....
```
attacker?

**Comment by josephtarbit** [comment]
What do you mean?

**Comment by TSaltedfishKing** [comment]
What does "performer" mean?
mean actor(演员) or attacker(攻击者)?

**Comment by TSaltedfishKing** [comment]
My English is not good, sorry

**Comment by TSaltedfishKing** [comment]
> What do you mean?

My English is not good, sorry

**Comment by josephtarbit** [comment]
The player doing the action.

**Comment by TSaltedfishKing** [comment]
> The player doing the action.

thank you
