### ISSUE TITLE
Null point exception when game is rendering

### ISSUE THREAD

**Issue by Kopla-BR** [nexusnode/crafting-dead#7]
It was detected when I was testing the modpack in **version** 0.0.4 alpha.

- Sometimes when the mod's HUD is rendered when join world:

> **Stack-trace warn**: "**Unexpected error**";
> **Light error-line**: "at com.craftingdead.core.client.ClientDist.handleRenderGameOverlayPre(ClientDist.java:587) ~[?:0.0.4-alpha] {re:mixin,re:classloading}";
> **Full error stack-trace**: https://pastebin.com/CqEtfWE1;
> **Full client log**:  https://pastebin.com/JbQqfN40;

I was using **forge-31.2.45** to run it and Optifine for better rendering performance.
(This happened **even without** using Optifine)

**Comment by josephtarbit** [comment]
This is a known issue, it's going to be fixed as part of a rewrite of some of the mod's internals.
