### ISSUE TITLE
why i cant change to zh_CN

### ISSUE THREAD

**Issue by TSaltedfishKing** [nexusnode/crafting-dead#73]
can you fix that 
can i join your team?

**Comment by josephtarbit** [comment]
Hmm, you should be able to. What exactly happens?

**Comment by TSaltedfishKing** [comment]
wait a min

**Comment by TSaltedfishKing** [comment]
My game is in Chinese，And I added zh_ch.json
used ci files
but still English

**Comment by TSaltedfishKing** [comment]
![image](https://user-images.githubusercontent.com/60768370/107132386-62f11e00-6919-11eb-81c3-3d5891634b08.png)

**Comment by josephtarbit** [comment]
Did you change the language in-game?

**Comment by TSaltedfishKing** [comment]
![image](https://user-images.githubusercontent.com/60768370/107132421-f296cc80-6919-11eb-8f68-28319fc419f1.png)
![image](https://user-images.githubusercontent.com/60768370/107132476-5de09e80-691a-11eb-9da7-7a6fae143063.png)
![image](https://user-images.githubusercontent.com/60768370/107132486-7650b900-691a-11eb-9135-686edae7d481.png)

**Comment by TSaltedfishKing** [comment]
> Did you change the language in-game?

yeah

**Comment by josephtarbit** [comment]
Ahh, I know why. You need to use lowercase for the file name so: zh_cn.json

**Comment by TSaltedfishKing** [comment]
> Ahh, I know why. You need to use lowercase for the file name so: zh_cn.json

it is zh_CN or zh_cn?

**Comment by TSaltedfishKing** [comment]
do you have discord account？

**Comment by josephtarbit** [comment]
It needs to be zh_cn
> do you have discord account?

Yes, it’s Sm0keySa1m0n#6763

**Comment by TSaltedfishKing** [comment]
> It needs to be zh_cn
> 
> > do you have discord account?
> 
> Yes, it’s Sm0keySa1m0n#6763

ok

**Comment by TSaltedfishKing** [comment]
can i create a crafting dead server ?

**Comment by TSaltedfishKing** [comment]
crafting dead was popular at 1.6.4 in China

**Comment by josephtarbit** [comment]
> can i create a crafting dead server ?

Of course.

**Comment by TSaltedfishKing** [comment]
than you

**Comment by TSaltedfishKing** [comment]
when now?

**Comment by TSaltedfishKing** [comment]
> It needs to be zh_cn
> 
> > do you have discord account?
> 
> Yes, it’s Sm0keySa1m0n#6763

i added you
