### ISSUE TITLE
Backpack problem and ammunition problem

### ISSUE THREAD

**Issue by Izmc1** [nexusnode/crafting-dead#79]
Some players keep changing the magazines, and the magazines become more and more. Change the magazines to the gun and then change the bullets in the gun to the empty magazines, so that you can keep refreshing the magazines.
If you put something in the vest A, then take off the vest A, put on the vest B with nothing, put on the vest A again, you will find that the contents disappear.

**Comment by josephtarbit** [comment]
There's currently some problems with ammo which we are waiting on a Forge update to fix, this will be rectified ASAP.

**Comment by Izmc1** [comment]
Thanks for replying.I'm looking forward to your good news

**Comment by Izmc1** [comment]
What about the vest problem? It makes the items disappear.We can't store items

**Comment by josephtarbit** [comment]
I’ll look into the problem with vests.

**Comment by josephtarbit** [comment]
Vests are fixed. Ammo is on the to-do list.
