### ISSUE TITLE
Unlimited crafting of combat knives

### ISSUE THREAD

**Issue by Liangbai2333** [nexusnode/crafting-dead#80]
If the player uses two combat knives to make new combat knives in the crafting table in survival mode and press the shift key, the player’s inventory will be filled with combat knives!

It seems that many knives are like this

Is it a mod bug? Hmm... it seems serious.

**Comment by josephtarbit** [comment]
I'll have a look into this, not sure what's going on there.

**Comment by josephtarbit** [comment]
Fixed.
