### ISSUE TITLE
About the parts of the gun.

### ISSUE THREAD

**Issue by Liangbai2333** [nexusnode/crafting-dead#84]
Unlimited access to gun parts: Load the gun with parts, then close the container of assembly parts, and the parts will be returned to players. Put the gun in the place of assembly parts, and the parts will still be displayed.(In single player mode)

Sometimes, put the parts into the gun, put them in the player inventory, and then turn off the player inventory. After a while, take them out, and the parts of the gun will be gone. I don't know if this is a problem with my server.(Forge version: 36.0.1)

**Comment by josephtarbit** [comment]
Can you check if this is fixed in 1.3.0?

**Comment by josephtarbit** [comment]
Closing until confirmed.
