### ISSUE TITLE
A bug about the gun unloading clip can be brushed

### ISSUE THREAD

**Issue by ghost** [nexusnode/crafting-dead#86]
Tested in the 1.16.5 original version. Press the J key to unload the magazine twice to brush the materials

**Comment by ghost** [comment]
Uploading 9BB9B7EAAE17CD698383AD6C93D56468.mp4…

**Comment by josephtarbit** [comment]
(Your video didn't upload) What do you mean by "brush"?

**Comment by ghost** [comment]
I'm sorry I will load video

**Comment by ghost** [comment]
https://user-images.githubusercontent.com/78008410/108350670-7bb5d980-721f-11eb-9015-87ba64698968.mp4

**Comment by ghost** [comment]
I am chinese I use Google Translate so You know

**Comment by josephtarbit** [comment]
I'm still not sure what is happening in that video.

**Comment by ghost** [comment]
Firearms can be retracted 2 times

**Comment by srlss123** [comment]
Can card unlimited bullets

**Comment by ghost** [comment]
Can be used as an infinite bullet

**Comment by ghost** [comment]
This bug is to press the shortcut key J, and then you can take a lot of  bullets

**Comment by ghost** [comment]
So I can pick up a gun and press the j key, and I can get unlimited bullets

**Comment by ghost** [comment]
English is not good, so please understand

**Comment by josephtarbit** [comment]
Ahh, I understand now. I know this is an issue, I'm waiting for a Forge PR to be merged until this can be fully fixed.

**Comment by TSaltedfishKing** [comment]
>  9BB9B7EAAE17CD698383AD6C93D56468.mp4

ok
