### ISSUE TITLE
Few Random bugs

### ISSUE THREAD

**Issue by denireilly** [nexusnode/crafting-dead#89]
- M4 Texture bug when holding it https://prnt.sc/zf6i7w
- Mini guns rotating everyone's instead of individual 
- Taser model is lol https://prnt.sc/zf3nb1 https://prnt.sc/zf3kln
- Supplydrop caller being a block "more of a server side issue with placing blocks"

- Traveller backpack possible paint skin issue

**Comment by josephtarbit** [comment]
Can you give me more detail on the last two

**Comment by denireilly** [comment]
Supply drop being a block, so with regions block placement isnt possible i dont think we would be able to use the supply drops as you are technically trying to place a block i might be wrong havent done much testing with it

Traveller backpack sometimes dosnt hold the paint data when storing guns, happened a couple of times wasn't able to reproduce instantly but could be an reoccurring issue down the line 

hope this helps

**Comment by josephtarbit** [comment]
Supply drops are an entity and see if that traveller's backpack issue is fixed in 1.3.0.

**Comment by denireilly** [comment]
i am talking about the supply drop callers lol

**Comment by josephtarbit** [comment]
Are miniguns still rotating everyone else's barrel?
