### ISSUE TITLE
[Feature request] Hit sound

### ISSUE THREAD

**Issue by ChromaPIE** [nexusnode/crafting-dead#90]
Now we got awesome hitmarkers, it would be even more awesome to add a sound together with the marker, just like COD and stuff!

**Comment by josephtarbit** [comment]
There's a sound for when you kill someone but we lowered the volume to ensure it's not too annoying.

**Comment by ChromaPIE** [comment]
> There's a sound for when you kill someone but we lowered the volume to ensure it's not too annoying.

I just noticed that there's a bullet_impact_flesh.ogg that plays when hit zombies. That's actaully good enough! And when it comes to the sound plays when entities got killed, seems like it's fixed as the sound getting the trident back. Could it be changed as customizeable, like via the config toml file?

(btw the flash blindness effect's localization is missing, showing its bare key name on Waila/TOP etc.)

**Comment by josephtarbit** [comment]
Yeah I'll add that and fix that translation.

**Comment by ChromaPIE** [comment]
Soorry for keep adding stuff here. Just don't feel like opening another issue just to ask that, can Crafting Dead have a config option that prevents itself from intervening vanilla crosshair rendering? This could be useful when using CD together with Shoulder Surfing. I do found it works already good with it, after a right click the screen zoomed in really cool, making me feel like playing The Division. but the crosshair went missing when aiming down sight and that's the only disappointing aspect but an option to make the mod honor the vanilla crosshair would be helpful. Btw if CD could somehow **support** Shoulder Surfing, then it'd be even more badass! sounds crazy so it's okay if been estimated unrealizeable.

**Comment by josephtarbit** [comment]
The crosshair is disabled when aiming down sights because there's no point having a crosshair if you're already looking through a sight on a gun. In addition, looking down the sight already zooms in the camera so showing the crosshair would give you even more of an advantage and there would then be little point using one of the scope attachments.

**Comment by ChromaPIE** [comment]
But as I've said above, when playing with Shoulder Surfing, showing no crosshair when aiming down sight could be a problem isn't it? Moreover I didn't see options about the thirst system in the config, could we have an option to disable the thirst (in order to let mods like Tough as Nails handle it), and more importantly, have a feature to add custom quenching food items to make it more modpack-friendly.

**Comment by josephtarbit** [comment]
Addressing this in #95.
