### ISSUE TITLE
report

### ISSUE THREAD

**Issue by wkurumi** [nexusnode/crafting-dead#91]
Mod monsters, no longer actively attack the player, version 1.3.0.

I'm using Arclight.

Plugin list：
[21:22:00] [Server thread/INFO] [Console/]: Plugins (37): LuckPerms, RandomParac
hute, PlaceholderAPI, PublicBin, CMILib, SnowkSpigotFixer, spark, ArmorStand-Lim
iter, BetterEnchantBook, RhyPay, TabooLib5, Patch4, ProtocolLib, CratesLottery,
ShulkerBoxFixer, LiveRecorder, MiaoBoard, NBTAPI, Vault, ReviveMe, MiaoChat, PVP
Control, ContinuousKill, KillEntityActivity, Multiverse-Core, AuctionHouse, Mone
yDrop, ServerSafetyManagement, ChestCommands, LockettePro, BanIt, OfferAReward,
CMI, CMIEInjector, UltimateClaims, MPoints, BossShopPro

Forge mods：
[21:24:05] [Server thread/INFO] [minecraft/DedicatedServer]: Mod List:
• minecraft forge-1.16.5-36.0.42-server.jar : minecraft (1.16.5) - 1
• mods_folder cityblocks-1.16.5-1.4.2.jar : cityblocks (1.4.2) - 1
• mods_folder Ping-1.16.4-1.6.9.jar : ping (1.16.4-1.6.9) - 1
• mods_folder ImmersiveEngineering-1.16.5-4.2.1-131.jar : immersiveengineering (
1.16.5-4.2.1-131) - 1
• mods_folder crafting-dead-core-1.16.5-1.3.0-alpha.jar : craftingdead (1.3.0-al
pha) - 1
• mods_folder jei-1.16.4-7.6.1.71 .jar : jei (7.6.1.71) - 1
• mods_folder Botania-1.16.4-411.jar : botania (1.16.4-411) - 1
• mods_folder car-1.16.5-1.0.3.jar : car (1.16.5-1.0.3) - 1
• mods_folder Guide-API-VP-1.16.4-2.2.1.jar : guideapi-vp (2.2.1) - 1
• mods_folder curios-forge-1.16.5-4.0.4.0.jar : curios (1.16.5-4.0.4.0) - 1
• mods_folder SpartanShields-1.16.4-2.1.1.jar : spartanshields (2.1.1) - 1
• mods_folder Patchouli-1.16.4-50.jar : patchouli (1.16.4-50) - 1
• mods_folder Waystones_1.16.3-7.3.1.jar : waystones (7.3.1) - 1
• mods_folder betterweather-1.2.9.jar : betterweather (1.2.8) - 1
• mods_folder polymorph-forge-1.16.5-0.24.jar : polymorph (1.16.5-0.24) - 1
• mods_folder TravelersBackpack-1.16.4-5.3.8.jar : travelersbackpack (5.3.8) - 1

• mods_folder hcdservercore-1.16.5-1.2.3.jar : hcdservercore (1.2.3) - 1
• mods_folder lostcities-1.16-4.0.7-beta.jar : lostcities (1.16-4.0.7-beta) - 1
• mods_folder worldedit-mod-7.2.3.jar : worldedit (7.2.3+5680-135941e) - 1
• mods_folder Vampirism-1.16.4-1.7.6 .jar : vampirism (1.7.6) - 2
• arclight arclight.jar : arclight (1.16.5-1.0.15-SNAPSHOT-242055d) - 1
• mods_folder VampiresNeedUmbrellas-1.16.4-1.1.jar : vampiresneedumbrellas (1.1)
 - 1
• mods_folder ImmersivePetroleum-1.16.4-3.1.0-2.jar : immersivepetroleum (3.1.0-
2) - 1
• maven_libs forge-1.16.5-36.0.42-universal.jar : forge (36.0.42) - 1
• mods_folder FastLeafDecay-v25.jar : fastleafdecay (v25) - 1
• mods_folder betterendforge-1.16.4-1.5.1.jar : betterendforge (1.16.4-1.5.1) -
1
• mods_folder EnderMail-1.16.5-1.2.0.jar : endermail (1.16.5-1.2.0) - 1
• mods_folder emotecraft-0.12.4_for_MC1.16.2+.jar : emotecraft (0.12.4) - 1
>

![image](https://user-images.githubusercontent.com/63358787/109812981-b419d680-7c67-11eb-8b6a-75ad25776bd0.png)

**Comment by josephtarbit** [comment]
Remove all mods and plugins and test if it works. All I can say is that Crafting Dead itself works just fine so it must be something else that you've added that is breaking it.

**Comment by wkurumi** [comment]
> 删除所有模块和插件，并测试其是否有效。我只能说Crafting Dead本身就可以正常工作，因此您添加的其他东西一定会破坏它。

Okay, zombies are not important anymore. Now I found a more troublesome bug. When I teleport between worlds, my thirst value will always drop blood, even if the thirst value is full, it will keep dropping blood.

**Comment by josephtarbit** [comment]
Can you confirm if this is still an issue?
