### ISSUE TITLE
Immerse Pre release not working

### ISSUE THREAD

**Issue by Annihilator4423** [nexusnode/crafting-dead#92]
Hello, I downloaded the crafting dead latest from releases and tried the crafting dead Immerse and receiving the following issue

![image](https://user-images.githubusercontent.com/61148120/110050966-9a859700-7d1a-11eb-9fb7-10a7b97ce1a2.png)

I am not sure what this is and the only mods I have installed are the crafting dead 1.3.0 1.16.5 and immersive 1.16.5-0.0.1-alpha

**Comment by Annihilator4423** [comment]
Actually that error seems to be just crafting dead. but If I downgrade to CD 1.2.9 It shows Crafting dead immersive instead,

the error message for immersive is:
![image](https://user-images.githubusercontent.com/61148120/110051238-15e74880-7d1b-11eb-8513-79547a31d6a7.png)

**Comment by Hallzmine** [comment]
You need to use crafting dead core NOT immerse. Also ensure that you have the latest version of forge installed.

**Comment by Annihilator4423** [comment]
Is Immerse not ready for testing yet? because the prerelease was on the releases page. so I wasn't sure.

**Comment by josephtarbit** [comment]
Immerse requires core 1.3.0 and you need the latest version of forge for 1.16.5.
