### ISSUE TITLE
Few feedbacks

### ISSUE THREAD

**Issue by ChromaPIE** [nexusnode/crafting-dead#95]
- Broken Leg effect doesn't seem to be always honoring fall damage modifiers: In the instance I've been playing with there are at least two mods that are modifying fall damage: Passable Foliage, making players falling on foliage blocks take configurable percentage of the normal damage, and Wall Jump, increasing the threshold of height players has to fall before taking fall damage, and seems like CD only take the very vanilla fall damage height into Broken Leg calculating, so when I fall from the height within the Wall Jump's threshold, or fall into foliage blocks, I got my legs broken, and even died from falling. However, what has been described above is simply from normal playing and hasn't been carefully double confirmed.
- The localization key of the message shown for death caused by Dehydration is missing.
- Bleeding effect, along with too many aspects of the already awesome mod, worths some more implemented configs, like whether it's enabled, and how it damages players (like time in ticks between each damages, and health point it bleeds per damage).

**Comment by josephtarbit** [comment]
- Disable thirst option.
- Configurable thirst quenching items.
- Configurable death sound.

**Comment by josephtarbit** [comment]
- Add flash blindness effect's localization

**Comment by ChromaPIE** [comment]
- Killing zombies from Crafting Dead isn't completing Monsters Hunted advancement.
- Make tooltips on thirst quenching items showing how much would they quench.
- Suggestion (may sound crazy): More than items that quench thirst, items that cause thirst after consuming would be nice to be introduced. Just set the value for vanilla food items(cookie, bread etc.) and just like what has been planned for thirst queching items, it should also be configurable.
