### ISSUE TITLE
About bugs on 1.16.4 server

### ISSUE THREAD

**Issue by UQRARA** [nexusnode/crafting-dead#97]
**I vray love this mods,But he seems to have a lot of bugs on the 1.16.4 server; Gameversion 1.16.4 Modversion 1.2.9**

When the server is equipped with firearms accessories, accessories will be lost ; 
The model of the gun is only half,It's hollow from the side ;

Can the server configuration of this module be changed
[DENY fracture; DENY bleeding; DENY Infected; Adjust the number of zombies]

thank you

**Comment by josephtarbit** [comment]
Update to 1.3.0

**Comment by UQRARA** [comment]
I'm real sorry
1.3.0 does not run successfully in 1.16.4

**Comment by josephtarbit** [comment]
Use 1.16.4, latest Forge. Pretty much all 1.16.4 mods will work on 1.16.5 anyway.

**Comment by UQRARA** [comment]
Thank you. I'll try


------------------&nbsp;原始邮件&nbsp;-----------------
发件人:                                                                                                                        "nexusnode/crafting-dead"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月12日(星期五) 下午5:33
***@***.***&gt;;
抄送:&nbsp;"UQ.rara"<3308868854@***@***.***&gt;;
主题:&nbsp;Re: [nexusnode/crafting-dead] About bugs on 1.16.4 server (#97)





 
Use 1.16.4, latest Forge. Pretty much all 1.16.4 mods will work on 1.16.5 anyway.
